src/Console/ModelsCommand.php
trying to generate doc for a model with dependencies in constructor will fail with `new $name` .
Now it works using `\App:make($name)` laravel IOC resolves the dependencies.
=> Model doc : create model using App::make($name)

src/Console/ModelsCommand.php
Hi Barry.
My Base Model has some of relations:
```php
/**
* Relation to the parent.
*
* @return BelongsTo
*/
public function parent()
{
return $this->belongsTo(static::class, static::PARENT_ID);
}
/**
* Relation to children.
*
* @return HasMany
*/
public function children()
{
return $this->hasMany(get_class($this), static::PARENT_ID);
}
```
It is incorrect result of `./artisan ide-helper:models -W` command
```php
/**
* ModelName
*
* @property-read static $parent
* @property-read \Illuminate\Database\Eloquent\Collection|\get_class($this)[] $children
*/
```
And it is expected result
```php
/**
* ModelName
*
* @property-read ModelName $parent
* @property-read \Illuminate\Database\Eloquent\Collection|ModelName[] $children
*/
```
The attached patch fix this.
=> Fixed class name resolution via get_class() and static::class.

src/Generator.php
[October CMS](http://octobercms.com/) built on laravel includes an Auth facade in its [RainLab.User](https://github.com/rainlab/user-plugin) plugin but the resolved class doesn't contain a *driver()* method - so `php artisan ide-helper:generate` gives a nasty error during execution. This PR checks for the existance of the method before attempting to use it.
Ideally I'd like to see your other if statements in this method include the same check, but for the moment this is the only one erroring so I only updated that line.
=> Check for driver method on Auth facade

src/Console/GeneratorCommand.php, src/Generator.php
Super frustratingly, October CMS RC uses `October\Rain\Config\Repository` instead of `Illuminate\Config\Repository` so your package is incompatible with it. Removing the typehints in the same way you've already done with your `$view` constructor argument fixes this problem and generators work fine again.
=> Add support for October CMS config

config/ide-helper.php
Hi Barry,
I have updated config so that it will map `Authenticatable` contract rather than `UserInterface` for the `App\User` model by default.
Thanks,
Matt
=> Authenticatable Contract for User model

resources/views/helper.php
I'm pretty sure it should be `a helper file` as opposed to `an helper file`
=> Indefinite article

config/ide-helper.php, src/Console/ModelsCommand.php
This adds an ability to have custom database types in your database and still have `ide-helper:models` generate correct documentation for them. 
For example, I extensively work with PostgreSQL `jsonb`, `array` and `point` types which are currently not mapped to a valid Doctrine type. This makes ide-helper skip the model entirely. With this PR you can just add the following to your ide-helper config file and have your models documentation generated just fine.
```php
'custom_db_types' => array(
'postgresql' => array(
'citext' => 'text',
'jsonb' => 'string',
'point' => 'text',
'array' => 'text',
'_int4' => 'string',
)
),
```
`jsonb` is mapped to a string for me (but you can have it mapped to array using `'json_array'` instead of `'string'`. `'_int4'` is used as an internal type for …
=> Custom database types support for L5 branch

src/Console/ModelsCommand.php
It's needed for chain calls like 
`Model::popular()->orderBy('id','desc') /* popular() here is scopePopular() in model class */`
=> Add Query\Builder return type to magic scope* methods

src/Console/ModelsCommand.php
If relation has other methods, generating doc is fail.
E.g.
```php
$this->belongsToMany('App\User')->withTimestamps();
```
generate this:
```
@property-read \Illuminate\Database\Eloquent\Collection|\App\User')->withTimestamps([] $users 
```
=> Bug fix with model relations

readme.md
Before
```bash
$ php artisan vendor:publish --provider=barryvdh/laravel-ide-helper --tag=config
Nothing to publish for tag [config].
```
After
```bash
$ php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config
Publishing complete for tag [config]!
```
=> Fix vendor:publish provider name

src/Console/ModelsCommand.php
This commit fixes the issue #240 
The issue takes place because we set --dir option with the folder that already in app folder, so the models are parsed from app folder and then from inner folder app/Models and that is why there are duplicates. As a workaround I add every parsed models to ignore list, so they will not be parsed twice.
=> fix model docBlocks duplicates

src/Console/ModelsCommand.php
The request fixes the issue #239 
The problem was in the strpos() in exploading argument list. It was looking for the first occurance of '(' which is in get_class($this), so it takes everything before ')' --> get_class($this. While in getClassName function strpos is checking - strpos($className, 'get_class($this)') !== false, so it fails. 
I have changed it to strrpos - in order to find the last occurance and explode the full argument list.
=> fix get_class($this) in relationship functions

src/Console/ModelsCommand.php
Add support for models that override Eloquent's `newCollection()` method with a custom collection type. Do this by executing the relationship on the model then executing that relationship's `newCollection()` method to see what type of collection class is returned.
This also removes the the now-unused `Barryvdh\LaravelIdeHelper\Console\ModelsCommand::getClassName()` method since relationship properties aren't determined with as much string logic as before. 
This change has one side-effect. Since it determines relationship property types by executing the relationship it now puts fully-qualified model class names into the classes' docblock tags instead of class alias names or class names without their namespace if the model and its related model are in the same namespace. For instance, what …
=> Add custom collection support

src/Method.php
Without this fix script fails:
[2015-12-11 16:44:33] local.ERROR: exception 'ErrorException' with message 'trim() expects parameter 1 to be string, resource given' in /home/nikolay-zakharov/PhpstormProjects/webhosts/project/vendor/barryvdh/laravel-ide-helper/src/Method.php:274
To reproduce:
https://gist.github.com/nikolay-zakharov/df3760693593df9dea3c
=> Fixed: fails to generate with resources

composer.json
Hi,
I made a quick change to the composer.json in order to allow symfony/class-loader 3.0 to be installed.
=> Allow symfony/class-loader 3.0 to be installed

src/Generator.php
This addresses issue #306 by loading the framework version using the right Application depending on Laravel/Lumen.
=> Add support for Lumen 5.0, 5.1 and 5.2+

src/Generator.php
In my Lumen app, I load my providers and aliases from a `config/app.php` file like in Laravel. Maybe that is uncommon, but this simple PR will include those aliases as well if any are present.
=> Look for additional facade aliases in app config array

src/Console/MetaCommand.php
This fixes completion in PhpStorm 2016.2+, and also works in PhpStorm 10. Note: despite needing the FQN in the .meta definition, you do not need to use it in your project to get autocomplete.
FQN is [now required for function references](https://youtrack.jetbrains.com/issue/WI-31102), closes #340.
Unfortunately, this does not fix the problem in 2016.1, as you still need to use the FQN `\app('foo')->` in your project to get autocomplete, but there's nothing we can do about that - it's a PhpStorm bug, and is now fixed in 2016.2 EAP.
=> Use FQN for app() methods

config/ide-helper.php, src/Console/ModelsCommand.php
Added support for camel case model properties, as I had previously requested in #312.
There are some Laravel packages (such as Eloquence) that allow for accessing Eloquent model properties via camel case, instead of snake case.
This PR adds in an option (default disabled), to support these packages by saving all model properties as camel case, instead of snake case.
For example, normally you would see this:
```
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
```
With this enabled, the properties will be this:
```
* @property \Carbon\Carbon $createdAt
* @property \Carbon\Carbon $updatedAt
```
It is currently an all-or-nothing option, as that was the simplest to implement and it suits my needs.
=> Allow for camel case model properties.

config/ide-helper.php, src/Console/ModelsCommand.php, src/Generator.php
This PR is to allow a developer to define the following in their `ide-helper.php` configuration:
```php
/*
|--------------------------------------------------------------------------
| Property Casts
|--------------------------------------------------------------------------
|
| Cast the given "real type" to the given "type".
|
*/
'type_overrides' => array(
'integer' => 'int',
'boolean' => 'bool',
),
```
This will replace `@property integer` with `@property int` when running `ide-helper:models`. This will satisfy the [phpdoc_scalar](https://styleci.readme.io/docs/fixers#phpdoc_scalar) fixer when using the Laravel preset on StyleCI.
This is also the scalar convention for Laravel and I would actually honestly consider changing `integer` to `int` and `boolean` to `bool` in the following …
=> Allow Type Overrides

readme.md
This pull request fixes the "Using $this when not in object context" bug for the Lumen configuration. Since the `bootstrap/app.php`-file is not in object context, and the `app` instance accessible using the `$app` variable directly, using `$this->app` will result in a fatal error.
=> Fix "Using $this when not in object context" bug

src/Console/ModelsCommand.php
This change allow to use return type from accessor's dockblock to specify parameter type in generated class-level docblock.
For example, for this class
```php
class Test extends Model
{
/**
* Test getter
*
* @return string
*/
public function getTestAttribute()
{
return 'test';
}
}
```
generated docblock will look like 
```php
/**
* Test
*
* @property-readonly string $test
* @mixin \Eloquent
*/
```
This small change will lead to better code completion and should improve developer's experience for those who have plenty of custom getters/setters.
=> Use accessor docblock return type to guess property type

src/Console/ModelsCommand.php
If a scope has a typehint, e.g.
```php
public function scopeBeforeDate($query, \Carbon\Carbon $date)
{
return $query->where('date', '<', $date->startOfDay()->toDateTimeString());
}
```
The docblock `@method` lacks the `\Carbon\Carbon` typehint. This pull request adds that missing functionality.
=> Scope parameter typehints

resources/views/helper.php, src/Alias.php, src/Generator.php
After PR #394 discussion I decided to make my own version in another way.
Facades with there methods are now declared in the same namespace as in Laravel. So you can use fullname of facades to import them : `use Illuminate\Support\Facades\Auth;` This is better for using ide-helper on an old project made without ide-helper. You don't need to replace fullnames anymore.
I also noted that autocompletion is improved for some librairies like Intervention : `Image::make()` result is now well autocompleted. It's surely due to the fact that now PHPStorm use Laravel docBlocks in association with the docBlocks in `_ide-helper.php`. For example, `Auth::user()` dont only return your user model but also `Authenticatable` like the original method.
To allow usage of short names, facades are also declared …
=> Add facades fullpath autocomplete

resources/views/helper.php, src/Alias.php
Fix a bug concerning PR #437 
The wrong classes were used for some facades like Eloquent.
Before :
````php
namespace Illuminate\Database\Eloquent {
class Eloquent {
namespace {
class Eloquent extends \Illuminate\Database\Eloquent\Model {}
````
After :
````php
namespace Illuminate\Database\Eloquent {
class Model { // <= Good
namespace {
class Eloquent extends \Illuminate\Database\Eloquent\Model {}
````
=> Fix facades fullpath autocomplete

resources/views/helper.php
'references()' and 'on()' argument names were backwards
As a reference:
https://laravel.com/docs/5.1/migrations#foreign-key-constraints
and a screenshot from PHPStorm with parameter name hints enabled:
=> Correct Fluent helper output

readme.md
I simply added a few lines regarding to enabling support for Laravel Fluent methods :)
=> Add documentation in readme.md for Laravel Fluent methods support

src/Console/ModelsCommand.php
Laravel 5.4
i have Intermediate Table Model (pivot) in my models directory and after run
php artisan ide-helper:models
I get error: 
Exception: Target [Illuminate\Database\Eloquent\Model] is not instantiable while building [class]
Could not analyze class
=> ignore custom intermediate table models ( Laravel 5.4 )

composer.json, src/Console/MetaCommand.php, src/Generator.php, src/IdeHelperServiceProvider.php
This should safeguard from app-dedicated overrides to the View Factory used in-app.
=> Decoupled from main app View Factory

src/Console/ModelsCommand.php
For issue https://github.com/barryvdh/laravel-ide-helper/issues/480
Explanation of changes:
`tinyint` is classified as `bool` by doctrine/dbal, but it should not be so in our use case. `tinyint` is better PHPDoc'ed as `int` (as it can be used for many reasons). **If the user wants `bool`, he should use Eloquent's `$casts` property to do that.**
I have therefore, moved doctrine/dbal's `boolean` to set the property type as `int` in PHPDoc.
=> Fix #480 where tinyint is casts as bool

src/Console/ModelsCommand.php
As discussed in #481 
Due to the changes, `pgsql`'s `boolean` became `int` too. This change uses Laravel's `config('database.default')` to determine the db type. Where it's the case that it is `pgsql`, it will use `boolean`.
[sqlite also uses int as boolean](https://sqlite.org/datatype3.html#boolean_datatype)
=> Add support for pgsql for boolean types

src/Console/ModelsCommand.php
This resolves #490, where the return type of a function would include the return description in the class-level docBlock.
Using the example in #490, the result will now correctly display as '* @property-read bool $example'.
=> Resolve displaying @return types with descriptions

composer.json, src/Console/ModelsCommand.php, src/Method.php
Hello @barryvdh ,
Can you please consider this Pull Request if it makes sense to you.
**Background:**
We are on Laravel 4 but have want to use some library which demand 3.1 version of `phpdocumentor/reflection-docblock` and we get conflict on version `1.11` of ide-helper because it uses `phpdocumentor/reflection-docblock": "2.0.4`.
So  I noticed your latest master branch where you are using your own fork of `barryvdh/reflection-docblock": "^2.0.4`. So I branched out from `1.11` and checked your fork of reflection-dockblock which seems to be working fine with 1.11 also.
For me I've forked your branch already but it would be great if you can merge it too. 
Thanks in Advance.
-Ahsan
=> Replaced the reflection-docblock with version of barryvdh

src/Alias.php, src/Macro.php
Generates stubs for marcos if the class uses the *Marcroable* trait.
=> Adds support for macros

src/Generator.php
fluent autocomplete is really useful, but I don't think it's a good idea to generate a config file for IDE helper package.
=> set `include_fluent` default to true

resources/views/meta.php, src/Console/MetaCommand.php
This commit adds support for the new [PhpStorm Advanced Metadata](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata) format.
What this allows us to do is to add autocompletion for the several (array) helper methods that Laravel offers:
I have also added support for the new `makeWith` and `resolve` functions.
The only thing that I think could be improved here is not having to hardcode the helper functions, but I couldn't think of a better way to handle it.
=> Use new PhpStorm advanced metadata format

resources/views/meta.php
After my last change to support the meta metadata format, I accidentally nuked the leading slash on the class names :(. This PR adds that slash back to fix autocompletion.
=> Add back leading slash on meta class names

config/ide-helper.php, src/Console/MetaCommand.php
PhpStorm supports putting multiple files in a `.phpstorm.meta.php/` directory. If you want to maintain multiple meta files, having to use the filename argument each time is a pain, so this makes that configurable.
=> Allow for configurable meta filename

src/Console/MetaCommand.php, src/IdeHelperServiceProvider.php
In a recent pull request https://github.com/barryvdh/laravel-ide-helper/commit/55c9bfc33b0e8fc35a8f7939f1d4afe5debf1eb3 checking configuration file for `meta_filename` was added, but there was no config object provided for the class so `Undefined property: Barryvdh\LaravelIdeHelper\Console\MetaCommand::$config` error was thrown. Now I've passed the app config object to the class and instantiated as such.
=> Bugfix: Undefined property: $config

.gitignore, .travis.yml, composer.json, phpunit.xml, readme.md, src/Alias.php, src/Console/GeneratorCommand.php, src/Console/MetaCommand.php, src/Console/ModelsCommand.php, src/Generator.php, src/IdeHelperServiceProvider.php, src/Method.php, src/PhpReflection.php, src/views/ide-helper.php, src/views/meta.php, tests/MethodTest.php, tests/ServiceProviderTest.php
* Add required composer dependencies for development such as `illuminate/config`, `illuminate/view`
* Correct spelling for README document
* Improve `MetaCommand` to support auto-completion in ArrayAccess mode (e.g. `$app['foo']`)
* Re-format and correct spelling for all source code
* Improve `Method` class to reduce generated filesize
* Correct FQN types for generated phpDoc by using PHP use statements
* Support case-insensitive `@inheritDoc` for phpDoc generation
* Reuse library "phpdocumentor/reflection-docblock" instead of custom one "barryvdh/reflection-docblock", because of using `setType` via PHP `ReflectionProperty`
* Add some `@noinspection` to generated file (_ide_helper.php) to bypass PhpStorm inspection
* And many stuffs :-)
=> Update to release v1.11.7

src/Eloquent.php
Hi,
This will fix the bug that has occurred since [Laravel removed the DocBlock](https://github.com/laravel/framework/commit/6f518a8a534702da9166ef2fc5e297a06ed5cc18). This fix ensures that all expected mixin entries are present.
Fixes #623
=> Fixes a bug where a missing DocBlock caused errors

readme.md
In Laravel 5.5, the `artisan optimize` command is deprecated, so this PR just removes it from the `readme.md`.
See https://laravel.com/docs/5.5/upgrade
=> The 'artisan optimize' command is now deprecated.

resources/views/helper.php
After some PhpStorm's update I noticed that it expects instance of `Illuminate\Support\mixed` as first argument of `default` method in migration files (see screenshot below).
I'm not sure if this is a PhpStorm's bug or something is wrong with my configs, but removing the `mixed` typehint (which is actually not an allowed typehint) fixes this inspection warning.
=> Remove `mixed` typehint from `Fluent::default` method

composer.json, src/Console/ModelsCommand.php
Closes #659.
Remove dependecy to Symfony\Component\ClassLoader\ClassMapGenerator and replace it with Composer\Autoload\ClassMapGenerator.
=> Replace Symfony ClassMapGenerator with Composer ClassMapGenerator

src/Console/ModelsCommand.php
The documentation for morphedByMany relationships was not generated by the ide-helper:models command as described in this issue: https://github.com/barryvdh/laravel-ide-helper/issues/593.
This PR resolves that issue.
=> Add morphedByMany relationship

src/Alias.php, src/Macro.php
Hi Barry,
We've been defining our macro's as callables of a class instead of using closures, sadly this breaks ide-helper because it expects only closures as macros.
This patch allows you to define methods like this as well: Str::macro('name', [$this, 'method']);
(This patch was based on the latest stable tag [2.4.1] because dev-master was broken for me, i'm not sure what branch you want me to push this to, if you want it on another branch so it's easier to tag please let me know)
=> Support php's array callable format for macro's.

src/Alias.php, src/Console/ModelsCommand.php
I really like to regenerate the complete set of properties and methods to keep everything sorted, but when I do that the text is removed. This adds an option somewhere in between (`-r` or `--smart-reset`) that transfers the text from the original docBlock to the new version, but discards all the rest.
=> "smart-reset": Reset properties/methods, but keep the text

src/Generator.php
For some reason facade Validator was commented and Gate was completely missing.
Since they can be used in the most recent of Lumen, I don't see why they shouldn't be included in ide-helper so PHPStorm can pick them up.
See https://github.com/barryvdh/laravel-ide-helper/issues/395 and https://github.com/barryvdh/laravel-ide-helper/issues/360
=> Added Validator and Gate facades for Lumen

src/Console/ModelsCommand.php
Allowing the `ide-helper:models` command to find and use pivot models. Fixing the problem in https://github.com/barryvdh/laravel-ide-helper/issues/253
=> Allow command to find and use pivot models

src/Console/MetaCommand.php
The getAbstracts() method may get $abstracts whose keys' order is not fixed from laravel application. It may result to the .phpstorm.meta.php file not be stable, it is a problem when commit this file to Git.
=> Sort keys for generating stable .phpstorm.meta.php

config/ide-helper.php, readme.md, src/Console/ModelsCommand.php
Laravel has a wrapper class for Carbon that it uses for model attributes in the `$dates` array and the `created_at` and `updated_at` attributes. This pull request changes all model docblocks to use the wrapper class instead of the base class.
=> Use Illuminate\Support\Carbon instead of Carbon\Carbon

src/Console/ModelsCommand.php
Hi @barryvdh,
When I use `artisan ide-helper:models`, it will have error when model's method has parameters and it also has relation.
Example (source [here](https://github.com/AsgardCms/Platform/blob/3.0/Modules/Media/Support/Traits/MediaRelation.php)):
```
/**
* Make the Many to Many Morph to Relation with specific zone
* @param string $zone
* @return object
*/
public function filesByZone($zone)
{
return $this->morphToMany(File::class, 'imageable', 'media__imageables')
->withPivot('zone', 'id')
->wherePivot('zone', '=', $zone)
->withTimestamps()
->orderBy('order');
}
```
So I suggest to ignore model's method that have parameter.
Regards,
Huy Dang
=> ide-helper:models error when model's method has parameters and also has relation

src/Console/ModelsCommand.php
The fix made in PR https://github.com/barryvdh/laravel-ide-helper/pull/614 for issue https://github.com/barryvdh/laravel-ide-helper/issues/253 was incorrect as it resulted in comments
no longer being generated for Models that are not Pivot Rlations.
This PR allow comments to be generated for both Pivot Models (as they are
a subclass of Eloquent\Model) and normal Models.
=> Only skip non-models when generating docs

resources/views/helper.php
refer to the documentation:
https://github.com/laravel/docs/blob/8e2065ebec9511677e60f2ad3bd6ecb6b79279c6/migrations.md#L283-L296
The `->nullable()` is allowing an argument.
=> nullable is actually support an argument

resources/views/helper.php, resources/views/meta.php, src/Console/ModelsCommand.php
The added comment with `//@formatter:off` isn't valid PHP code. There must be a space/enter between the php opening tag and the comment. PHPStan crashes/cries at this. This fix will make PHPStan happy again!
=> bugfix - Space/Enter between starting php tag and comment for PHPStan

src/Console/ModelsCommand.php
This PR adds support for `::query` and comparable methods. It fixes #692.
=> Add ::query support

resources/views/helper.php, src/Alias.php, src/Macro.php, src/Method.php
This PR fixes problem, described in #712 
Also, there is avoided code duplication in Macro constructor which makes me confusing why it is different if there nearly all code is the same.
=> Fix missed methods with same name

resources/views/helper.php, src/Alias.php
I noticed that there is missed autocomplete for variables in **helpers** view.
For me, as a new guy in this project, it was unclear what vars in view are and which methods are called.
So I added type binding and now it's much easier for new contributors to figure out what's going on here.
=> Fix missed autocomplete in helper view

src/Generator.php
`Barryvdh\LaravelIdeHelper\Generator::getAliases()` has its own logic for Lumen which does not have an `AliasLoader` class.
There is processing to check the existence of alias class. In the `$facades` array the key is alias class name and value is original class name so` array_filter` makes a judgment on whether there is an original class, not an alias class.
This patch is to correct this problem.
Fixes #698
=> Fix alias class existence determination #698

src/Method.php
In https://github.com/barryvdh/laravel-ide-helper/commit/5d8d93273f67797f61b92cc32690d058b6c6b4d9, an issue was introduced causing syntax errors to appear for methods defined in Macro's.
See issues: https://github.com/barryvdh/laravel-ide-helper/issues/726, https://github.com/barryvdh/laravel-ide-helper/issues/734
This is caused by trying to retrieve the real method name of an anonymous function (a closure).  Closures do not have a method name that makes sense to use in the ide_helper
file. e.g. `Illuminate\Foundation\Providers\{closure}` would be the real_name instead of
just `validate`. So for the closure methods, we should just use the provided
methodName instead.
=> bugfix - Do not use the real_name for closures

src/Alias.php
This pull request fixes issue https://github.com/barryvdh/laravel-ide-helper/issues/739.
The getMethods function gets called both in the removeDuplicateMethodsFromPhpDoc
function and in helper.php, which causes the method detection to be performed twice.
Parts of the method detection includes a check for duplicate methods, but Macro
methods for example, aren't checked for duplicates.
Instead of checking everywhere if we're not adding duplicates, I've included a
check in the getMethods call to just use the already generated methods
if they have been generated already.
=> bugfix - Prevent redeclaring methods inside Aliases

composer.json
This PR should solve the second part of #739.
This update improves the parsing of return types, allowing array return
types to be recognized.
This was needed to properly recognize the files and allFiles methods as
duplicates (the function filtering duplicate definitions - `removeDuplicateMethodsFromPhpDoc` in `Alias.php` - didn't recognise them as duplicates, because the return type was seen as part
of the name).
=> Update ReflectionDocBlock to v2.0.6

.travis.yml
The composer update takes about 12 minutes, which is just over the
10 minute timeout in Travis.
=> bugfix - Increase composer update timeout in Travis

src/Generator.php
"laravel/framework": "5.7.*"
config/database.php
```php
'redis' => [
'client' => 'phpredis',
'default' => [
'host' => env('REDIS_HOST', '127.0.0.1'),
'port' => 6379,
'database' => 0,
],
],
```
config/app.php
```php
'aliases' => [
// ....
'RedisServer'  => Illuminate\Support\Facades\Redis::class,
]
```
=> if aliases not Redis, don't skip

config/ide-helper.php, src/Console/GeneratorCommand.php, src/Eloquent.php
Hi,
This will solve the problem from #699, #697 and #695.
This patch will not completely disable the addition of mixins like https://github.com/barryvdh/laravel-ide-helper/commit/7db1843473e1562d8e0490b51db847d3a1415140, but make them optional.
It would be really wonderful to continue to have this option as it greatly simplifies the work. But since not everyone wants `/vendor` files to be changed, this behavior is now optional.
The changes to add the mixins are the same as in #624 .
Best,
Patrick
---
Fixes: #715 #716
=> Optionally write missing Laravel Model DocBlock

src/Console/ModelsCommand.php
This change fixes a bug where when there is a parameter taken by a relationship 
`getPropertiesFromMethods` function will return instead of going to next method on the list.
=> Fix: Parametrized relationships prevent generation of metadata

src/IdeHelperServiceProvider.php
If views are disabled in application an error is encountered:
```
In Container.php line 767:
Class view does not exist
```
This pull requires will prevent loading views in `IdeHelperServiceProvider` if there is no `view` binding in application container.
=> Prevent loading views if `view` class not in container

resources/views/helper.php, src/Method.php
When calling the original method, I would like to use static call or instance method call, as appropriate.
Also, want to resolve the return type when it was $this.
current:
("Non-static method 'withGlobalScope' should not be called statically" warning in PHPStorm)
("Return value is expected to be 'Eloquent', 'Illuminate\Database\Eloquent\Builder' returned" warning in PHPStorm)
```php
/**
* Register a new global scope.
*
* @param string $identifier
* @param \Illuminate\Database\Eloquent\Scope|\Closure $scope
* @return $this
* @static 
*/ 
public static function withGlobalScope($identifier, $scope)
{
return \Illuminate\Database\Eloquent\Builder::withGlobalScope($identifier, $scope);
}
```
Idea
```php
/**
* Register a new global scope.
*
* @param string $identifier
* @param …
```
=> fix: warning when call the instance method

composer.json
I use "laravel/framework": "dev-master as 5.7.999" (alias because of the <5.8 of laravel-ide-helper) and it works perfectly so I assume, there is no real reason to lock this project compatibility to <5.8
=> Allow Laravel 5.8

config/ide-helper.php, src/Alias.php, src/Generator.php
Currently if a class has magic methods and the class include type hints they aren't resolved by the ide-helper package.
For example before:
and after:
My proposed PR simply inspects classes, includes their DocBlocks to add in any comments and PhpDoc including @method's to allow type hinting.
=> Include DocBloc’s from classes to allow deeper code inspection

src/Alias.php
Macros can be used with invokable classes, like so.
```php
<?php
namespace App\Providers;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Response;
class ResponseMacroServiceProvider extends ServiceProvider
{
public function boot()
{
Response::macro('foo', new Foo());
}
}
class Foo
{
public function __invoke()
{
return 'foobar';
}
}
```
When running `ide-helper:generate` the following fatal error was thrown.
>Symfony\Component\Debug\Exception\FatalThrowableError  : ReflectionFunction::__construct() expects parameter 1 to be string, object given
This commit fixes this error.
=> Add support for invokable classes as macro function

src/Console/ModelsCommand.php
fix error on line l 483: 
Exception: stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
Could not analyze class App\Models\Client.
=> Fix php 7.3 bug

src/Console/MetaCommand.php
This is a nice-to-have ([as I'm currently overriding it](https://github.com/psalm/laravel-psalm-plugin/commit/a700c89061d151d1c08851abd93d834f9183534d)), but might help other packages.
=> Make autoload exception more specific

src/Alias.php
See my comment https://github.com/barryvdh/laravel-ide-helper/pull/765#issuecomment-471014271:
The change in #765 made anonymous functions get reflected with `ReflectionMethod` instead of `ReflectionFunction`, which makes it lose the doc comment. This means that the generated helpers are missing their return types. This is because Closure is also an object and callable.
To fix it, Closure should be excluded from that new condition.
Edit: More specifically, I think it's because `ReflectionMethod` tries to grab doc comments from `__invoke`, but the comment is actually at the location of the function, not in the Closure instance.
=> Fix regression introduced in #765

src/Console/ModelsCommand.php
You can override the builder class used on a per model basis. This wasn't supported yet.
For reference: https://mobile.twitter.com/timacdonald87/status/1109964446766497793
=> Support for custom builder classes

src/Console/MetaCommand.php, src/Console/ModelsCommand.php
It may throw an error instead of an exception for some classes.
=> use Throwable instead of Exception

readme.md
While installing this for my project, I didn't see the `--dev` instructions until I was literally editing this README for a pull request.
Since laravel-ide-helper is only designed for development purposes, let's just remove the superfluous entry altogether. Smart devs who for some crazy reason need it on prod will know to remove the `--dev`, while less knowledgeable devs won't shoot themselves in the foot accidentally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/barryvdh/laravel-ide-helper/786)
=> Removed confusing README installation instructions

src/Console/ModelsCommand.php
* x to Many relationships are detected via a `Many` keyword in the relationship object class name
* reason: example: `belongsTo` was incorrectly recognized as `belongsToMany`
* adds `@property-read int|null $x2Many_relationship_method_name_count` model class docBlock comment
* when model makes use of `withCount` or `loadCount` there is a property on the resource `$instance->relationship_method_count` that states the count of related models
* can be `NULL` when `withCount` or `loadCount` aren't used
=> Chages to x2Many relationships detection & adds $relationship_countt

src/Console/ModelsCommand.php
Some packages such as https://github.com/mad-web/laravel-enum allow using a class name as the cast type instead of setting up an accessor. 
If this is the case, the overrides will allow a call to `->castedProperty` to return an instance of whatever the class was e.g.
```php
class MyModel extends Model
{
use EnumCastable;
protected $casts = [
'status' => \App\Enums\MyModelStatusEnum::class
];
}
```
Calling `$model->status` will return an instance of `MyModelStatusEnum`.
This small patch means that if the provided cast type is a valid class name then rather than returning 
```php
@property mixed $status
```
We will assume it will return an instance of that class and so instead we output 
```php
@property \App\Enums\MyModelStatusEnum $status
```
In the event that the developer actually …
=> Add support for custom cast classes

src/Console/MetaCommand.php
When running `php artisan ide-helper:meta` in a Laravel project where [Lighthouse](https://lighthouse-php.com/) is installed, the `.phpstorm.meta.php` file contains syntax errors because it tries to add the classname of an anonymous class.
This line is what is added to the file:
```php
'Nuwave\Lighthouse\Support\Contracts\ProvidesSubscriptionResolver' => \class@anonymous /var/www/html/scorecardapi/vendor/nuwave/lighthouse/src/LighthouseServiceProvider.php0x7f67abf68775::class,
```
In this pull request, anonymous classes are not added to the `.phpstorm.meta.php` file
=> Do not add instances of an anonymous class to the phpstorm_meta file

src/Console/ModelsCommand.php, src/Method.php
This update changes the param type in methods to `[]` rather than `array()` as part of PSR-12 as enabling the new inspections in PHPstorm highlights this as an issue.
e.g.
```php
* @method static \Illuminate\Database\Eloquent\Builder|\App\Something whereHasTags($tags = array())
```
becomes
```php
* @method static \Illuminate\Database\Eloquent\Builder|\App\Something whereHasTags($tags = [])
```
=> [PSR-12] Update param type array to use short array syntax

src/Console/ModelsCommand.php
Added missing relation type.
Currently no doc line generated from hasOneThrough relation.
```
public function company()
{
return $this->hasOneThrough(
Company::class,
CompanyUser::class,
);
}
```
Expected result:
```
* @property-read \App\Models\Company $company
```
=> Add hasOneThrough to ide-helper:models

config/ide-helper.php, readme.md, resources/views/helper.php, resources/views/meta.php, src/Alias.php, src/Console/MetaCommand.php, src/Console/ModelsCommand.php, src/Factories.php, src/Generator.php
Right now, PhpStorm does not know what the return type of `factory(\App\User::class)->create()` is. To solve this, this PR adds two generators (when `include_factory_builders` is set to `true`):
First, the `generate` command will create "faux" FactoryBuilder classes, like:
```php
namespace App {
/**
* @method \Illuminate\Database\Eloquent\Collection|User[]|User create($attributes = [])
* @method \Illuminate\Database\Eloquent\Collection|User[]|User make($attributes = [])
*/
class UserFactoryBuilder extends \Illuminate\Database\Eloquent\FactoryBuilder {}
}
```
Second, the `meta` command will override the `factory()` method to return the associated builder class:
```php
override(\factory(0), map([
'' => '@FactoryBuilder',
'App\User' => \App\UserFactoryBuilder::class,
]));
```
Now, PhpStorm …
=> Add support for factory()->create() return types

src/Console/ModelsCommand.php
Laravel 5.8 introduced a feature to support a custom date class via
`Date::use()`, see https://github.com/laravel/framework/pull/25320
When e.g. using `Date::use(CarbonImmutable)` in a project, it means
all date casts are not returning `\Illuminate\Support\Carbon` anymore
but `\Carbon\CarbonImmutable`, which means all the generated type hints
for dates are now wrong.
This change tries to be still backwards compatible with Laravel < 5.8
which do not have the Date facade.
=> Add support for custom date class via Date::use()

.gitignore, .travis.yml, composer.json, tests/Console/EloquentCommandTest.php, tests/MethodTest.php, tests/TestCase.php
I don't know how others feel, but many of my projects _depend_ on this library.
Eventually I would like to contribute, give back something to this great idea of the author and the community. My PR https://github.com/barryvdh/laravel-ide-helper/pull/859 was merged and I really wanted to write a test, but I realized: there is nothing (ok, 2 tests…) but also no infrastructure for running these kind of tests (Laravel framework setup, models to test, etc;) 😢 
Laravel packages whose functionality depends on the Laravel framework cannot easily be tested just with PHPUnit alone and usually require https://github.com/orchestral/testbench
- (chore: moved tests into a dedicated `Tests` namespace)
- removed phpunit and added orchestral/testbench (which itselds depends on PHPUnit…)
- picked one small …
=> [PROPOSAL] Add more tests to the library

.travis.yml, composer.json, tests/Console/EloquentCommandTest.php, tests/TestCase.php
Based on the feedback in https://github.com/barryvdh/laravel-ide-helper/pull/865#issuecomment-570085281 I _tried_ to come up with a possible solution here:
This is mostly driven by two factors:
- Everything < PHP 7.2 is **not** supported anymore => https://www.php.net/supported-versions.php
- In light of expanding the test suite, many recent versions of tools have 7.2 as minimum requirement
As such, the changes summarized here are:
- drop support for < 7.1 and explicitly bump php verison in `composer.json `
- rework the travis test matrix **to be explicit**
- Previously it was unclear what was really tested because only the PHP version was specified and all the dependencies aligned itself, but that didn't express what Laravel version was actually tested => this is now explicit
- as such …
=> Drop support for PHP < 7.2 and improve test matrix

composer.json
The current version emits the following:
```
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in laravel-ide-helper/vendor/phpro/grumphp/src/Locator/ConfigurationFile.php on line 75
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in laravel-ide-helper/vendor/phpro/grumphp/src/Locator/ConfigurationFile.php on line 75
```
Manually tested it locally, worked as expected.
=> [CHORE] Bump grumphp version

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Models/Simple.php, tests/Console/ModelsCommand/Relations/Test.php
If the property name matches the foreign key name creating a BelongsTo relation triggers an undefined property error. Disabling constraints prevents accessing the property and thus prevents the error.
This is a workaround for an issue in Laravel that may or may not be fixed (see https://github.com/laravel/framework/issues/31098). However since we don't actually need the constraints it seems worth disabling them to prevent the underlying issue from surfacing?
Resolves #484.
=> Prevent undefined property errors

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Test.php
This is the same as https://github.com/barryvdh/laravel-ide-helper/pull/804 **without** the refactoring (and adapting the tests).
I don't thin that refactoring so many lines in contrast for a single line change makes sense and could be the reason this wasn't merged already.
Note: I cherry-picked the original commit, which means @markokeeffe as the author **is kept**.
=> Fixed bug in model command where loose string comparison would override properties for model relations

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Models/Simple.php, tests/Console/ModelsCommand/Relations/Test.php
=> Fixed #892

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GenerateBasicPhpdocCamel/Models/Post.php, tests/Console/ModelsCommand/GenerateBasicPhpdocCamel/Test.php
=> Fix camelCase duplicated properties generator.

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/SoftDeletes/Test.php
These two methods are already regular methods on the trait, there's no
need to add them and additionally they're not static, so their
definition was changed for the worse.
The other methods are magic so it's fine to keep them.
Fixes https://github.com/barryvdh/laravel-ide-helper/issues/917
=> Remove unnecessary and wrong definition of SoftDelete methods

src/Console/MetaCommand.php
I brought this up in #915 
Without removing our custom autoloader in `MetaCommand.php`, subsequent php code executed in the same process will trigger this autoloader, preventing any usage of `class_exists()` calls.
If you have any advice on how to write a regression test for this, please feel free to advise! I did pull this commit into  my codebase where i was running into the autoloader problem, and it seemed to fix it.
=> fix: unregister meta command custom autoloader when it is no longer needed

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Getter/Models/Simple.php, tests/Console/ModelsCommand/Getter/Test.php
Up until now, to have the `get…Attribute` return a useful type information in the class phpdoc, it was **necessary** to specify the `@return` annotation; otherwise the result was always `mixed`.
This now adds the capability to derive the type from the reflection itself.
- Example:
```php
function getFooAttribute(): string
{
}
```
- before ` * property-read mixed $foo`
- after ` * property-read string $foo`
Note that the docblock is still the *authoritative* source _if_ provided. The reason is that phpdoc expressiveness / supporting tooling still exceeds PHPs type capabilities.
But this also means if the docblock is wrong, so will the type be and this PR won't fix that.
OTOH it removes the need for a docblock for the simple cases (e.g. no iterables of a type).
Tests with lots-o-variations …
=> Infer return type from reflection if no phpdoc given

src/Method.php, tests/MethodTest.php
Certain default values for method parameters (strings containing single quotes or trailing backslashes) currently generate an invalid `_ide_helper.php` file.
This PR fixes that by replacing the current naïve code generation with a call to `var_export()`.
=> Prevent generation of invalid code for certain parameter default values

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/PHPStormNoInspection/Models/Simple.php, tests/Console/ModelsCommand/PHPStormNoInspection/Test.php
When using write option for models eq
```bash
php artisan ide-helper:models --smart-reset --write 
```
Generated PHPDoc has fully qualified names, about which PHPStorm complains (as it should). However, this is problematic since later during automatic code cleanup tasks these names are replaced with `use` statements. This generates unnecessary changes in the files, especially if some developers forget to run code cleanup. Later on, all of this stays in the git history.
As a solution, this PR adds a new option to the model command. `--phpstorm-noinspections` eg
```bash
php artisan ide-helper:models --smart-reset --write --phpstorm-noinspections
```
This will include two PHPStorm inspections at the end of the PHPDoc comment
```
* @noinspection PhpFullyQualifiedNameUsageInspection
* …
```
=> Generate noinspections PHPStorm tags

src/Console/ModelsCommand.php
Example: app/Services/*/Models
=> Ability to use patterns for model_locations

src/Method.php, tests/MethodTest.php
Fixes #923 
So this is an attempt to add `static` to the return type on the builder methods generated by `ide-helper:generate`. I am not 100% sure if this is the right location for this but it wasn't immediately obvious where else it could go. 
I have tested this on a number of my projects and it works as expected.
_ide-helper.php_
```php
* @return \Illuminate\Database\Eloquent\Builder|static
...
public static function where($column, $operator = null, $value = null, $boolean = 'and')
```
Unfortunately the Generator command doesn't have any tests - which is understandable due to its complexity. But I have added a test for the `Method` class I have changed
=> Add static return type to builder methods

src/Generator.php
some project may not need Auth service provider
#649
=> Test `auth` is binded before detect Auth driver

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GenerateBasicPhpdoc/Test.php, tests/Console/ModelsCommand/GenerateBasicPhpdocCamel/Test.php
To follow Eloquent casts
Closes https://github.com/barryvdh/laravel-ide-helper/issues/417
=> Decimal columns as string in Models

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GenerateBasicPhpdocFinal/Models/Post.php, tests/Console/ModelsCommand/GenerateBasicPhpdocFinal/Test.php
fixes #766 
I've added a search for `final class {ModelClass}` before searching for `class {ModelClass}` and changed the `substr_replace()` call to simply inject the doc-block instead of replacing the whole `class ...` string.
This made it easier to use both search needles and don't adjust the replace string.
=> Fix inline doc-block for final models

.github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml, composer.json, grumphp.yml, psalm-baseline.xml, psalm.xml, src/Alias.php, src/Console/MetaCommand.php, src/Generator.php
👋 Any interest in introducing a static analysis tool like psalm? I currently set it to the least strict setting, but can make more prs tightening it up if that is of any interest
=> [Chore] Introduce psalm

.gitattributes, .github/workflows/run-tests.yml, README.md
I.e. some of the not-yet-implemented feedback from https://github.com/barryvdh/laravel-ide-helper/pull/960
- clean up mention of travis
- prefer composer scripts for final execution
- use env var for no-interactive
- adjust .gitignore exports
- separate non-matrix job for phpcs
Oh, and gave the workflow file a name so it appears more nicely in e.g. https://github.com/barryvdh/laravel-ide-helper/actions
=> Small improvements for github actions

composer.json, grumphp.yml
👋 I think this should allow usage with composer 2. There isn't an official tag yet, so `^2.0@dev` should suffice to allow dev stability versions of the release. Naturally once the official composer 2 release is made, we should update the dependency to be `"composer/composer": "^1.6 || ^2.0",`
------
I have verified that our (ide-helper's) usage of composer is limited to `ClassMapGenerator::createMap`, whose signature doesn't seem to have changed in composer 2.
------
`grumphp` added support for composer 2 in [`0.18.1`](https://github.com/phpro/grumphp/pull/768), hence why I have updated it in this PR.
Related: https://github.com/psalm/psalm-plugin-laravel/issues/89
=> [Chore] Composer 2 support

README.md
As requested per https://github.com/barryvdh/laravel-ide-helper/pull/961#discussion_r443749363
> Can we add the Actions badges?
GHA badges are "per workflow" and we got three, but I figured the most relevant one is about the tests.
=> [README] Add gha badge for tests

.github/workflows/composer-normalize.yml, .github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml
Prevent things like https://github.com/barryvdh/laravel-ide-helper/pull/958/checks?check_run_id=796677164 where jobs runnaway for up to 6 hours (GHA default timeout…)
I figured if within 15 minutes it's not done, there's a problem anyway.
=> [GHA] Add timeouts

composer.json, grumphp.yml
This reduces the # of places we need to change configurations for various dev tools. Now grumphp will just execute the composer script listed under the `script` key.
I updated grumphp because this later version has support for running various different composer scripts
=> chore: use composer scripts in grumphp

.github/workflows/run-tests.yml
Also drop dedicated testbench version, composer can figure it out itself
https://laravel.com/docs/7.x/releases#support-policy
Only 5.5 receives security fixes until 2020-08-30,
everything else < 6 isn't supported anymore.
Therefore I dropped all versions not officially
supported.
I also find the change in the matrix more readable without having to
mentally parse a set of a lot "includes",
I think this clarifies the intent better.
This also results in more jobs are more (correctly allowed) variations are now covered.
=> [GHA] Drop non-supported Laravel versions and simplify matrix

config/ide-helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/MagicWhere/Models/Post.php, tests/Console/ModelsCommand/MagicWhere/Test.php, tests/Console/ModelsCommand/RelationCountProperties/Models/Post.php, tests/Console/ModelsCommand/RelationCountProperties/Test.php
Accidentally fucked up https://github.com/barryvdh/laravel-ide-helper/pull/837 by deleting the branch or force-pushing (can't reopen), so here's a new PR.
I've rebased on top of current master, added a test for `write_model_relation_count_properties` and also added another test for `write_model_magic_where` while I was at it.
CC @mfn
=> Make writing relation count properties optional

src/Console/GeneratorCommand.php
It has been marked as deprecated for 7 years (!) and the option isn't
used in the current code, i.e it does nothing.
=> Remove deprecated sublime option

composer.json
We only support L5.5 which is satisfied by testbench 3.5 already
=> [COMPOSER] Reduce constraints for testbench

README.md
@barryvdh after https://github.com/barryvdh/laravel-ide-helper/issues/408 I wondered if it still makes sense to have those old files linked? I think nowadays it's common/accepted that users simply use the package and generate the files?
=> Removed old/outdated gists from readme

README.md, config/ide-helper.php
Whilst working through hundreds of issues I made note of some recurring patterns (like [custom_db_types](https://github.com/barryvdh/laravel-ide-helper/issues?q=is%3Aissue+custom_db_types+)) to follow-up to improve the README where some of the available configuration options are not mentioned.
Overview of the changes:
- remove mention of sublime command (which itself has been removed in https://github.com/barryvdh/laravel-ide-helper/pull/976 )
- update phpstorm link to regading `.phpstorm.meta.php` (old link only redirects, use the destination link directly)
- mention that the default _ide_helper.php name can be changed
- document `meta_filename` and hint it can be written into a special subdirectory
- remove hint about \Eloquent or `@mixin`, as the latter is automatically added nowadays …
=> Improve readme in certain areas

src/Console/ModelsCommand.php
Ensures they're always ordered / processed independent of the
environment. `ClassMapGenerator::createMap` uses symfony/finder which
itself supports sorting but this isn't used from the `ClassMapGenerator`.
We don't have tests but I tested this in a private project successfully.
- Fixes https://github.com/barryvdh/laravel-ide-helper/issues/885
=> Sort models found in file system

src/Generator.php
- support for < L5.5 was dropped, so no need to check if it's >= Laravel 5.2
- for the same reason, the Lumen 5.0/5.1 check isn't necessary because only supporting Laravel 5.5 means we only support the Laravel 5.5 _components_ which means the minimum supported Lumen version is also 5.5 (per https://lumen.laravel.com/docs/master/releases#5.5.0 )
**TL;DR:** Nowadays we an just call `\Auth::guard()` directly and don't worry
There no tests for this, so I tested this codechange in a private Laravel project successfuly
=> Remove unnecessary version checks due to unsupported old Laravel/Lumen versions

src/Console/MetaCommand.php
Some years ago the Laravel container was made PSR compliant and this
attributes to the fact that `->get()` is a valid resolve call too.
=> Add more methods able to resolve container instances

resources/views/helper.php, resources/views/meta.php
In https://github.com/barryvdh/laravel-ide-helper/pull/990#issuecomment-664590457 it was agreed upon to just remove them.
=> Remove timestamps in generated files

README.md
I've tested this and yes, it *always* requires a FQN.
Therefore I removed the extra note regarding namespace/wrapping because
even by default Laravel has the `App\` namesapce, which requires this.
Fixes https://github.com/barryvdh/laravel-ide-helper/issues/995
=> [README] Be clear that models require FQN

tests/Console/ModelsCommand/CustomCollection/Test.php, tests/Console/ModelsCommand/CustomDate/Test.php, tests/Console/ModelsCommand/GenerateBasicPhpdoc/Test.php, tests/Console/ModelsCommand/GenerateBasicPhpdocCamel/Test.php, tests/Console/ModelsCommand/GenerateBasicPhpdocFinal/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqn/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/Test.php, tests/Console/ModelsCommand/Getter/Test.php, tests/Console/ModelsCommand/Ignored/Test.php, tests/Console/ModelsCommand/Interfaces/Test.php, tests/Console/ModelsCommand/LaravelCustomCasts/Test.php, tests/Console/ModelsCommand/MagicWhere/Test.php, tests/Console/ModelsCommand/PHPStormNoInspection/Test.php, tests/Console/ModelsCommand/RelationCountProperties/Test.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/ResetAndSmartReset/Test.php, tests/Console/ModelsCommand/SoftDeletes/Test.php, tests/TestCase.php
Discovered via https://github.com/barryvdh/laravel-ide-helper/pull/1017#issuecomment-679318764
This only happens if you run an artisan command _before_ `runCommand`,
but since every of these tests performs migrations, using artisan,
the mocked output instance is left behind and also affected us.
The call added in `runCommand` explicitly unregisters
`\Illuminate\Console\OutputStyle` and thus also throwing away possibly
mocked versions.
=> [TESTS] Ensure output mocking is disabled so we can actually catch the output 😅

composer.json, src/Alias.php, src/Console/GeneratorCommand.php, src/Console/ModelsCommand.php, src/Eloquent.php, src/Macro.php, src/Method.php
This PR is cleaning low hanging fruits to bring it up to date:
- Correct typos
- Optimise if-else branches to reduce indentation
- Remove Docblocks for functions which contain type definitions.
- Cleanup unused params and namespace imports
Please feel free to comment and suggest other approaches.
=> Fix typos; Optimise if-else branches

.github/workflows/run-tests.yml
Run on push to master only, not other ones (avoids double runs when pushing to a separate branch)
=> Avoid duplicate tests

.github/workflows/run-tests.yml, composer.json, tests/MethodTest.php
Let's drop old Laravel versions and start testing Laravel 8
=> Bump Laravel versions

src/IdeHelperServiceProvider.php, tests/Console/MetaCommand/MetaCommandTest.php, tests/Console/ModelsCommand/AbstractModelsCommand.php, tests/TestCase.php
- Make createLocalViewFactory compatible with Laravel 8
- move `mockFilesystem` up so we can use it in other tests
- add a (really basic) test for `ide-helper:meta`
- Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1024
=> Make createLocalViewFactory compatible with Laravel 8

.gitignore
- `build` isn't used AFAIK?
- add `/` prefix were we know they're only expected to be in the root anyway
except `.phpunit.result.cache` which may appear anywhere it's run from
=> Improve gitignore a bit

config/ide-helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/Models/Post.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php
=> Add option to force usage of FQN

CHANGELOG.md, README.md, src/Generator.php, src/Macro.php
I have added macro support for all macroable classes, not only the alias classes.
But this only works if the macros are declared in any loaded service provider and type hinting is used.
Also no description is possible, only parameter and return types.
=> Add better support for macros and mixins

composer.json, psalm-baseline.xml
Now that Laravel 8 release, the baseline has to be set again:
- add a composer script to conveniently set the baseline
- run it and thus update the baseline
=> [PSALM] Update baseline

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/DynamicRelations/Test.php
Improves https://github.com/barryvdh/laravel-ide-helper/pull/1017 slightly
Instead of swallowing any error, we give visible feedback so users are actually aware why we skipped relations.
Inspired from analyzing https://github.com/barryvdh/laravel-ide-helper/issues/724
Not necessary, it's a minor thing
=> Give feedback when a relation can't be resolved

CHANGELOG.md, src/Helpers.php, src/IdeHelperServiceProvider.php
Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1042
Got broken by https://github.com/barryvdh/laravel-ide-helper/pull/1026
TL;DR: can't use anything in the `Illuminate\Foundation` namespace
without safety check, as it doesn't exist in Lumen.
=> Fix compatibility with Lumen

CHANGELOG.md, src/Macro.php
This PR adds an `@see` with the macro/mixin definition location to PhpDoc.
Logic:
```
class CollectionServiceProvider
{
public function boot(): void
{
\Illuminate\Support\Collection::macro('toEloquent', function(): \Illuminate\Database\Eloquent\Collection {
return \Illuminate\Database\Eloquent\Collection::make($this);
});
}
}
```
IDE helper:
```
/**
* @see \Collection\CollectionServiceProvider::boot()
* @return \Illuminate\Database\Eloquent\Collection
* @static
*/
public static function toEloquent()
{
return \Illuminate\Support\Collection::toEloquent();
}
```
Logic:
```
/**
* @mixin \Illuminate\Support\Collection
*/
class CollectionMixin
{
public function toEloquent(): Closure
{
return function(): \Illuminate\Database\Eloquent\Collection {
return …
```
=> Add @see location for macros & mixins to PhpDoc

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/AllowGlobDirectory/Services/Post/Models/Post.php, tests/Console/ModelsCommand/AllowGlobDirectory/Test.php, tests/Console/ModelsCommand/AllowGlobDirectory/__snapshots__/Test__test__1.php
This if statement check for a valid directory was happening to early.  It was checking the string that contained the wildcards to see if it is a valid directory and always failing.  Need to check after the foreach starts. fixes #1058 .
Glob patterns currently don't work.  The if statement that checks if the path is a directory happens before the glob helper call.
=> allow model_locations to have glob patterns

CHANGELOG.md, src/Alias.php
This should fix the issue https://github.com/barryvdh/laravel-ide-helper/issues/1065
=> Fix generate error when macroable class has a "fake" method

.github/workflows/composer-normalize.yml, .github/workflows/fix-code-style.yml, .github/workflows/run-integration-tests.yml, .github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml, composer.json, resources/views/helper.php
- switch from `ubuntu-latest` to `ubuntu-20.04`, i.e. be explicit and avoid running into suddenproblems when Github changes them
- be explicit for tests we require PDO Sqlite
- fix integration tests for Lumen not working with the new leagure/flysystem 2 (I just required `^1` for now)
=> [GHA] Misc improvements

.github/workflows/run-integration-tests.yml, .github/workflows/run-tests.yml, CHANGELOG.md, composer.json, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/DynamicRelations/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqn/__snapshots__/Test__test__1.php
- the codebase seems compatible except the one place where a deprecated `ReflectionParameter->getClass()` was called
- replaced it with `->getType()`
- seems it also improve the type declarations which are generated (test `GeneratePhpdocWithFqn`)
- Lumen 6 and 7 don't support PHP8, so excluded from integration tests
- friendsofphp/php-cs-fixer is (not yet) PHP 8 compatible, thus removed it from the unit tests matrix
Same was already done for vimeo/psalm in the past
- mockery minimum version had to be bumped to 1.3.3 for PHP8 compat
figured the bump is fine as it's a dev dependency only anyway
- spatie/phpunit-snapshot-assertions required `^4` for PHP8 compat, so it's added
- in one test we checked the literal PHP errors, which changed from PHP < 8 and PHP 8, so added an `if` condition to …
=> [PHP8] Add initial compatibility

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/ExtendedSelfCastingCasterWithStaticDocblockReturn.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/ExtendedSelfCastingCasterWithThisDocblockReturn.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/SelfCastingCasterWithStaticDocblockReturn.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/SelfCastingCasterWithThisDocblockReturn.php, tests/Console/ModelsCommand/LaravelCustomCasts/Models/CustomCast.php, tests/Console/ModelsCommand/LaravelCustomCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____custom_casts_table.php
Right now a cast cannot specify that it returns static or this.
Allowing so would mean a new cast can extend the old one without having to redefine the get method (e.g. an Enum)
Presently if you specify static/this in the return type then those values are literally used which makes a property look like it returns an instance of the model itself.
=> Allow casts with a return type of static or this to reference themselves

README.md, config/ide-helper.php, resources/views/helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/Builders/PostExternalQueryBuilder.php, tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/Models/Post.php, tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/Test.php, tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/Builders/PostExternalQueryBuilder.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/Models/Post.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php
#887 
Added a new feature where we create a helper file with external eloquent builders [Reference](https://timacdonald.me/dedicated-eloquent-model-query-builders/). 
This is very useful as in my big projects I do use this feature and so does some people -- [Issue](https://github.com/barryvdh/laravel-ide-helper/issues/887).
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] This change requires a documentation update 
- [ x ] Misc. change (internal, infrastructure, maintenance, etc.)
- [ x ] Existing tests have been adapted and/or new tests have been added
- [ x ] Update the README.md
- [ x ] Code style has been fixed via `composer fix-style`
- [ x ] Tested
=> Add support for dedicated eloquent builders and type/doc parameter support.

CHANGELOG.md, config/ide-helper.php, src/Console/GeneratorCommand.php, src/Generator.php
The JSON generate doesn't work, always generates an empty list.
I looked a bit around and seems changes around 3 years ago broke it.
Since there was no bug report ever about this, I conclude this feature
isn't used and suggest to remove it.
This also changes the config `filename` as there's no need for the
extension-less version and the format is gone too. This change is
backwards compatible as we just add back the `.php` in case it's missing
though users are encouraged to update it.
- Fixes https://github.com/barryvdh/laravel-ide-helper/issues/979
=> Remove format and broken generateJsonHelper

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/Builders/PostExternalQueryBuilder.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php
Since both [Pull request 1106](https://github.com/barryvdh/laravel-ide-helper/pull/1106) and [Pull Request 1089](https://github.com/barryvdh/laravel-ide-helper/pull/1089) created retrieving type in a different manner therefore the type of a variable was put twice as a type hint. In the [Pull Request 1089](https://github.com/barryvdh/laravel-ide-helper/pull/1089) the type hinting is added, along with checking if there is a supported type hint inside of a doc block.  
Merged the two type fetching methods and combined them along with the dock block type fetching.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Existing tests have been adapted and/or new tests have been added
- [ x ] Code style has been …
=> Fix broken test "GeneratePhpdocWithExternalEloquentBuilder"

src/Alias.php, src/Macro.php, tests/AliasTest.php, tests/MacroTest.php
The `\Illuminate\Database\Eloquent\Builder` is also `Macroable` but doesn't use the standard `Macroable` trait and for this reason, its macros are not included in `helper.php`. This PR fixes it.
Fixes: #1070
=> `Alias` will grab macros from `\Illuminate\Database\Eloquent\Builder` too

src/Macro.php, tests/MacroTest.php
The #1006 added support for macros but lost the content of the original docblock that was useful to provide an actual description, params, and return types. This PR fixes it:
- If the closure has a docblock it will be saved
- `@param`s will be added only when the original docblock doesn't have them
- `@return` will be added only when the original docblock doesn't have it
Fixes #1099
=> `Macro::initPhpDoc()` will save original docblock if present.

.github/workflows/run-integration-tests.yml, .github/workflows/run-tests.yml, CHANGELOG.md, composer.json, tests/Console/ModelsCommand/LaravelCustomCasts/Test.php, tests/MethodTest.php
Based on the discussion around https://github.com/barryvdh/laravel-ide-helper/pull/1094#issuecomment-738611427
❗ BLOCKED UNTIL A NEW 2.8 RELEASE WAS MADE AND SOME TIME PASSED (like, a week) ❗ 
- some Laravel framework version checks in the tests are now be able to be removed
- I have not checked in detail, but judging by https://github.com/barryvdh/laravel-ide-helper/blob/db53e8e2b5868fb05019ae20e727be24831b46d8/README.md#auto-completion-for-factory-builders
> Deprecated for Laravel 8 or latest
we might be able to remove that part => will be a separate PR anyway, let's keep this one as minimal as possible
=> [2.9] Drop support for: Laravel 6, Laravel 7, PHP 7.2 and add doctrine/dbal ^3

CHANGELOG.md, src/Macro.php, src/Method.php, tests/MacroTest.php
Fix issues with parsing invokable macros (#1084).
- Bug fix (non-breaking change which fixes an issue)
Existing tests pass, but I expect that new tests must be added. Could you help me or point me in the right direction?
=>  Fix issues with parsing invokable macros

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Factories/Test.php, tests/MacroTest.php
Fixes the ordering of the phpdoc for the test assertion, making master branch green again.
=> tests: fix assertion

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Factories/Test.php
As the title says. Just a minor thing to keep the changelog in order so it's correct for the next release and can be copy pasted.
=> changelog: re-order entry after recent merges in master

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/UnionTypes/Models/UnionTypeModel.php, tests/Console/ModelsCommand/UnionTypes/Test.php, tests/Console/ModelsCommand/UnionTypes/__snapshots__/Test__test__1.php
This PR addresses issue #1129 , fixing exceptions thrown when a union type is present both in return type and parameter types
In php 8 ReflectionType class is subclassed by ReflectionUnionType , which is missing getName() and isBuiltin() methods. This code changes aim at defining an intermediary function that:
- handles ReflectionUnionTypes by splitting them in an array of ReflectionNamedTypes.
- handles single ReflectionNamedTypes, wrapping them in an array in order to handle the same data type
```php
protected function extractReflectionTypes(\ReflectionType $reflection_type)
{
if($reflection_type instanceof \ReflectionUnionType){
foreach ($reflection_type->getTypes() as $named_type){
if($named_type->getName()==='null'){
continue;
}
$types[] = $this->getReflectionNamedType($named_type); …
```
=> Fix broken ReflectionUnionTypes

.php_cs.common.php, src/Alias.php, src/Console/ModelsCommand.php
PSR12 ruleset has been added in v2.18.0. https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.18.0
Changed @PSR2 to `@PSR12` in `.php_cs.common.php`.
I also enabled the commented out `allow_single_line_anonymous_class_with_empty_body` as it is already implemented in php-cs-fixer.
----
If you have any problems, you can of course close this PR.
=> Apply "@PSR12" in php-cs-fixer

CHANGELOG.md, README.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Comment/Models/Simple.php, tests/Console/ModelsCommand/Comment/Test.php, tests/Console/ModelsCommand/Comment/__snapshots__/Test__test__1.php
In order to better support ide, relations and getters/setters can also add comments like table columns. Only based on DocBlock, use `@comment`.[#1165](https://github.com/barryvdh/laravel-ide-helper/issues/1165#issue-818725732)
- getter
- setter
- scope
- relations
=> Add comments like table columns.

composer.json, config/ide-helper.php, src/IdeHelperServiceProvider.php, src/Listeners/GenerateModelHelper.php
This pull request allows generating model helpers automatically after migrations executed.
Basically a newer version of #842, started from the current master branch.
Based on the comment by barryvdh the config option is simplified it is named `post_migrate` and it is either false to disable this feature or sets the parameters for the "ide-helper:model" command. It supports both `"--nowrite"` and the `["--nowrite" => true]` format.
The trigger was updated to use the MigrationsEnded event because Laravel will run "incomplete" commands like `migrate:roll` as `migrate:rollback`.
The other helper file generation was dropped in favor of composer post update commands.
=> Auto generate models

src/Generator.php
This PR adds default values so array_merge does not break when config values are missing. This should not happen unless the package is freshly installed and config is cached.
Fixes #1180
=> Add default values to array_merge

CHANGELOG.md, psalm-baseline.xml, src/IdeHelperServiceProvider.php
This PR skips post migrate hooks when application is running unit tests. This should not cause any problems but it's unnecessary to generate the helpers hundred times. Also test should not have a sideeffect.
=> Skip post_migrate when running tests

CHANGELOG.md, README.md, config/ide-helper.php, src/Console/ModelsCommand.php, src/Contracts/ModelHookInterface.php, tests/Console/ModelsCommand/ModelHooks/Hooks/CustomProperty.php, tests/Console/ModelsCommand/ModelHooks/Models/Simple.php, tests/Console/ModelsCommand/ModelHooks/Test.php
In the last couple of Laravel projects I did, I needed extra IDE help for models (translated properties, attachments, etc.). There currently is no way to generate custom information so I wrote a model hook system. Everyone can then easily extend the generation of model information. In order to make it  actually useful, I changed some methods in the models command from protected to public.
=> Model hooks

CHANGELOG.md, README.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/ModelHooks/Hooks/CustomMethod.php, tests/Console/ModelsCommand/ModelHooks/Hooks/UnsetMethod.php, tests/Console/ModelsCommand/ModelHooks/Test.php
Expanding PR #945 to include support in ModelHooks to unset and set Methods.
This can be useful for defining class inheritance properly for the IDE.
=> Allowing Methods to be set or unset in ModelHooks

CHANGELOG.md, src/Console/MetaCommand.php, tests/Console/MetaCommand/MetaCommandTest.php
Bug fix for #1069.
Unregisters the autoloader registered via `MetaCommand->registerClassAutoloadExceptions` by reference instead of assuming it is the last registered autoloader.
I'm marking this as a "breaking change" because the `MetaCommand->registerClassAutoloadExceptions` is protected and I've changed the return type from void to callable (which is the registered autoloader). If you'd prefer, can solve without modifying method definition.
=> Fixing issue where incorrect autoloader unregistered (#1069)

CHANGELOG.md, tests/Console/MetaCommand/MetaCommandTest.php
- Mostly releases https://github.com/barryvdh/laravel-ide-helper/pull/1198 which has a small breaking change
- As per https://github.com/barryvdh/laravel-ide-helper/pull/945#issuecomment-813001854 we'll push the minor forward
=> chore: prepare 2.10.0 release

config/ide-helper.php
Documentation has been moved, old reference landing on 404.
Pointed to 2.x as for the moment we end up with 2.x because of many other package dependencies.
Updating old reference to DBAL types in config file
=> Fix link to DBAL types

.github/workflows/run-tests.yml
IMHO it's impractical to expect this package to have to work with the
"first release of Laravel for any major release" even when there are
already sever more releases: no one is/should stick to that version.
This is a re-submit of https://github.com/barryvdh/laravel-ide-helper/pull/1076
See also for recent breakaes
- https://github.com/barryvdh/laravel-ide-helper/pull/1216#issuecomment-831029022
- https://github.com/barryvdh/laravel-ide-helper/pull/1185#issuecomment-831029353
Note: PHP8 already didn't include it
=> composer.json: remove --prefer-lowest

CHANGELOG.md, src/Console/ModelsCommand.php, src/Generator.php, tests/Console/ModelsCommand/Factories/Factories/ModelWithNestedFactoryFactory.php, tests/Console/ModelsCommand/Factories/Models/ModelWithNestedFactory.php, tests/Console/ModelsCommand/Factories/__snapshots__/Test__test__1.php
Parent traits are not checked when checking for HasFactory or Macroable traits.
E.g; My models extend an AbstractModel which implements the HasFactory trait, but no documentation is added.
=> Check for traits recursively

CHANGELOG.md, src/Console/ModelsCommand.php
Use platformName instead of default connection name to determine used dbms. Previous solution isn't working, when custom names are used.
This should fix the problem mentioned in https://github.com/barryvdh/laravel-ide-helper/issues/480 for custom connection names, too. Example config/database.php section:
'default' => env('DB_CONNECTION', 'main_db'),
'connections' => [
'main_db' => [
'driver' => 'mysql',
'host' => env('DB_HOST_MAIN', '127.0.0.1'),
'port' => env('DB_PORT_MAIN', '3306'),
'database' => env('DB_DATABASE_MAIN', ''),
...
=> Use platformName to determine db type

src/Macro.php
In certain situations no enclosingClass can be found, quick fix is to just return then.
=> fix when no enclosingClass can be found

CHANGELOG.md, README.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Variadic/Models/Simple.php, tests/Console/ModelsCommand/Variadic/Test.php, tests/Console/ModelsCommand/Variadic/__snapshots__/Test__test__1.php
This adds support of variadic paremeters in ModelsCommand.
New feature
@mfn Where should I add some tests?
Thanks
=> Support variadic parameters in models command

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/Models/Post.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php
When using write-mixin, FQN is not generated for classes used in the Model. #1173
=> Fix #1173 Use FQN for write-mixin

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Models/BelongsToVariation.php, tests/Console/ModelsCommand/Relations/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____belongs_to_variation_table.php
When we run ide-helper:models on a class that defines a method that uses belongsTo, if the foreign key used for the relation is not null, a doc comment will be generated with the property returned as the relation class.
```php
<?php
use Illuminate\Database\Eloquent\Model;
/**
* @property-read App\User $user  <- returned type is relation class
* @mixin \Eloquent
*/
class Phone extends Model
{
public function user()
{
return $this->belongsTo('App\User');
}
}
```
However, there are times when we want to get the relation class **without using the foreign key constraint**, so we check for the existence of the relation class.
Therefore, static analysis with the current doc comments will fail, with the null check always resulting in false.
```php
$phone = Phone::firstOrFail();
if …
```
=> Consider foreign key constraints with isRelationNullable

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/SimpleCasts/Models/SimpleCast.php, tests/Console/ModelsCommand/SimpleCasts/Test.php, tests/Console/ModelsCommand/SimpleCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____simple_casts_table.php
Provides support for all missing types for `Model::$casts` including `decimal:*`, `custom_datetime`, `encrypted:*`, `immutable_date`, and `immutable_custom_datetime`. Resolves #1257 
- [ n/a ] Update the README.md
=> Improve casts support

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Attributes/Models/Simple.php, tests/Console/ModelsCommand/Attributes/Test.php, tests/Console/ModelsCommand/Attributes/__snapshots__/Test__test__1.php
This PR adds support for the new Attribute syntax added in Laravel 8.77, added by https://github.com/laravel/framework/pull/40022.
Using Reflection on the get/set method provided to the Attribute, we can determine the return type of the getter and setter.
Below is an example usage (also found in added test).
```php
use Illuminate\Database\Eloquent\Casts\Attribute;
class Users extends Model
{
public function name(): Attribute
{
return new Attribute(
get: function (?string $name): ?string {
return $name;
},
set: function (?string $name): ?string {
return $name === null ? null : ucfirst($name);
}
);
}
}
// => after generate models
/**
* App\Models\Users
* 
* @property string|null $name
* …
*/
```
This PR should be non breaking, but will however require laravel/framework >= 8.77 to work.
=> Support Laravel 8.77 Attributes

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Attributes/Models/Simple.php, tests/Console/ModelsCommand/Attributes/__snapshots__/Test__test__1.php
#1289 calls `getReturnType` for every method on every model, which in
turn calls `getReturnTypeFromDocBlock` which has this code:
```php
$phpDocContext = (new ContextFactory())->createFromReflector($reflection);
```
Extracting the docblock is super slow, always has been. Now that we do
this for every method, this adds up a lot.
Performance on a private commercial project _before_ #1289 was introduced:
```
$ time ./artisan ide-helper:models --write --reset >/dev/null
real	0m2.857s
user	0m1.835s
sys	0m0.129s
```
After #1289 :
```
$ time ./artisan ide-helper:models --write --reset >/dev/null
real	0m54.147s
user	0m47.132s
sys	0m1.047s
```
However, in this case we **do not need** the phpdoc fallback (which is
legitimate and by design for many other cases), because also the Laravel …
=> Improve performance for supporting Laravel 8.77+ cast attributes

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/CastableReturnsAnonymousCaster.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/CastableReturnsCustomCaster.php, tests/Console/ModelsCommand/LaravelCustomCasts/Models/CustomCast.php, tests/Console/ModelsCommand/LaravelCustomCasts/__snapshots__/Test__test__1.php
This PR added support for `Castable` interface. See https://github.com/laravel/framework/pull/32129 and [it's documentation](http://laravel.com/docs/8.x/eloquent-mutators#castables) for details about `Castable`.
- `castUsing` method might return an anonymous `CastsAttribute` class. In order to determine the return type, execute `castUsing` is required.
- When using anonymous class, seems like `ContextFactory` won't detect correct context, thus I'm passing the class that implements `Castable` for context detection.
=> Support Castables

.github/workflows/fix-code-style.yml, .github/workflows/run-integration-tests.yml, .github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml, CHANGELOG.md, composer.json
- Added Laravel 9 Support to `composer.json` and tests
=> added laravel 9 support

resources/views/helper.php
PHPCS is a common development tool. It makes sense to disable it in addition to Eclipse/IntelliJ formatting disable
=> Disabled PHPCS

composer.json, src/ClassMapGenerator.php, src/Console/ModelsCommand.php
This replaces the dependency on composer/composer and just uses the copy of the classmap generator (slightly modified).
=> Replace composer with copy of classmap generator

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/SimpleCasts/Models/SimpleCast.php, tests/Console/ModelsCommand/SimpleCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____simple_casts_table.php
Add support for the serialization options for Carbon instances. Adds tests. Resolves [#1322](https://github.com/barryvdh/laravel-ide-helper/issues/1322)
=> Add support for Carbon serialization options

.github/workflows/run-integration-tests.yml, CHANGELOG.md, src/Console/MetaCommand.php
- The issue was that on PHP 8.1, `new ReflectClass` does not silently swallow `null` values anymore as it did before
- This already happened but usually wasn't visible unless `-v` was used, example
```
$ ./artisan ide-helper:meta -v
Cannot make 'Faker\Generator': Class 'Faker\Provider\en_US\Barcode' not found.
Cannot make 'Illuminate\Contracts\Auth\Authenticatable': Class  does not exist
Cannot make 'cache.psr6': Class 'Symfony\Component\Cache\Adapter\Psr16Adapter' not found.
Cannot make 'csp-nonce': Class 'Wza3Mf4CXIvCkcp9K3boMUGJoK6S9maO' not found.
Cannot make 'env': Class 'local' not found.
Cannot make 'filesystem.cloud': Disk [s3] does not have a configured driver.
Cannot make 'redis.connection': Redis connection [default] not configured.
A new meta file was written to …
```
=> Fix integration tests by fixing a PHP 8.1+ deprecation warnings in ReflectionClass

CHANGELOG.md, README.md, config/ide-helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Models/Simple.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/Relations/Traits/HasTestRelations.php, tests/Console/ModelsCommand/Relations/Types/SampleToAnyMorphedRelationType.php, tests/Console/ModelsCommand/Relations/Types/SampleToAnyRelationType.php, tests/Console/ModelsCommand/Relations/__snapshots__/Test__test__1.php
Custom Relation types can be added using the config `additional_relation_types` already, but in the backend the return types for those relations is determined by using a simple check determining if the class name has `Many` in it to decide the return type of the relation.
This works for the built-in Laravel relations where they are named properly but packages like https://github.com/staudenmeir/eloquent-json-relations use a name such as `belongsToJson` to return a many relationship. This change allows a config option to specify the actual return type of the relation such as many or morphTo
=> Implement new config to specify return type of custom relations

src/Console/ModelsCommand.php
Hello,
Thanks for the package.  It's very helpful.
This PR fixes an issue with the model IDE helper generation command explained in https://github.com/barryvdh/laravel-ide-helper/issues/1120.  The command does not work with databases that use schemas such as postgres.  This is from the way the `explode` is computed to calculate the `database` and `table` name.  The `explode` needs to be restricted to the first instance of `.`.
Old Behavior (Bugged)
| Table String         | Database | Table     |
|----------------------|----------|-----------|
| `cats`               | null     | `cats`    |
| `mysql.cats`         | `mysql`  | `cats`    |
| `pgsql.animals.cats` | `pgsql`  | `animals` |
New Behavior:
| Table String         | Database | Table          | …
=> Allow for proper database resolve with schemas

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/SoftDeletes/__snapshots__/Test__test__1.php
Fix return type of methods provided by `SoftDeletes`.
The `SoftDeletes` model has three methods available:
* [withTrashed()](https://github.com/illuminate/database/blob/v9.0.0/Eloquent/SoftDeletingScope.php#L85-L91)
* [withoutTrashed()](https://github.com/illuminate/database/blob/v9.0.0/Eloquent/SoftDeletingScope.php#L102-L109)
* [onlyTrashed()](https://github.com/illuminate/database/blob/v9.0.0/Eloquent/SoftDeletingScope.php#L121-L129)
As the linked code shows, they return `\Illuminate\Database\Eloquent\Builder`, but the`ide-helper:models` command generates the annotation `\Illuminate\Database\Query\Builder`. I fixed this difference.
Previously there were no issues, but with the fix for [Laravel v9.3.0](https://github.com/laravel/framework/pull/41276) , some static analysis tools such as …
=> Fix return type of methods provided by `SoftDeletes`

src/Console/ModelsCommand.php
The models command is broken due to the last commit in https://github.com/barryvdh/laravel-ide-helper/pull/1349. The `getName` method returns the connection name instead of the database name.
=> Fix database name in ModelsCommand

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/InboundAttributeCaster.php, tests/Console/ModelsCommand/LaravelCustomCasts/Models/CustomCast.php, tests/Console/ModelsCommand/LaravelCustomCasts/__snapshots__/Test__test__1.php
This PR adds support for custom cast classes that implement the CastsInboundAttributes interface ( https://laravel.com/docs/9.x/eloquent-mutators#inbound-casting). Currently the Cast class will incorrectly end up as return value of the attribute.
=> Add support for CastsInboundAttributes

CHANGELOG.md, resources/views/meta.php
This adds some PhpStorm metadata to help with the return type when calling the `$this->mock`, `$this->partialMock` etc. methods in tests. By default PhpStorm believes the return type is an object implementing `MockInterface`, but this PR adds an additional typehint for the mocked class.
Here is an example in a test:
```
$user = $this->mock(User::class);
```
PhpStorm will now say the return type is `App\Models\User&Mockery\MockInterface`.
=> Add phpstorm metadata for mock methods when testing

.github/workflows/run-integration-tests.yml, .github/workflows/run-tests.yml, composer.json
This pull request will add support for Laravel 10.
=> Added support for Laravel 10

.github/workflows/composer-normalize.yml
We don't need to enable it in the project itself, but at least in this workflow which explicitly uses it.
See https://github.com/barryvdh/laravel-ide-helper/actions/runs/3980013548/jobs/6822812621#step:4:34
```
Error: ergebnis/composer-normalize (installed globally) contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
You can run "composer global config --no-plugins allow-plugins.ergebnis/composer-normalize [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)
```
=> gha: fix workflow by allowing the composer-normalize plugin

composer.json, psalm-baseline.xml, src/Generator.php
SSH facade has removed from Laravel 5. It doesn't exist in supported Laravel versions:
- https://github.com/laravel/framework/tree/v8.83.27/src/Illuminate/Support/Facades
- https://github.com/laravel/framework/tree/v9.48.0/src/Illuminate/Support/Facades
- https://github.com/laravel/framework/tree/10.x/src/Illuminate/Support/Facades
=> Bump Psalm version

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/LaravelCustomCasts/Models/CustomCast.php, tests/Console/ModelsCommand/LaravelCustomCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____custom_casts_table.php
Let's say we have the following custom cast:
```php
class MyCustomCast implements CastsAttributes
{
/**
* @param Model                $model
* @param string               $key
* @param mixed                $value
* @param array<string, mixed> $attributes
* @return SomeObject|null
*/
public function get($model, string $key, $value, $attributes): ?SomeObject
{
if ($value === null) {
return null;
}
return new SomeObject($value);
}
// setter omitted from example for brevity
}
```
Now suppose we have two pretty much identical models which use this cast:
```php
class ModelA extends Model
{
protected $table = 'models_a';
/**
* @var array<string, string>
*/
protected $casts = [
'casted_column' => MyCustomCast::class,
];
}
```
```php
class ModelB extends Model
{
protected $table = 'models_b';
/** …
```
=> Refactor resolving of null information for custom casted attribute types

src/Alias.php
- Credit goes to @dongm2ez
- Re-do of https://github.com/barryvdh/laravel-ide-helper/pull/1432
- Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1431
=> Catch error and exception (#1431)

.github/workflows/composer-normalize.yml, .github/workflows/fix-code-style.yml, .github/workflows/run-integration-tests.yml, .github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), update to node 20
This PR updates the GitHub Actions from **V2** to **V4**.
All annotated warning link to the official GitHub documentation: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
[actions/checkout/releases/v4.0.0](https://github.com/actions/checkout/releases/tag/v4.0.0)
=> ci: Use GitHub Actions V4

.github/dependabot.yaml
Inspired by https://github.com/barryvdh/laravel-ide-helper/pull/1469 , so we don't need to "think" about keeping things update.
This deliberately only targets GHA and not e.g. `composer`. As a library I believe we want the widest and not the narrowest dependencies, so neither minor nor major updates make sense to me (for now, at least).
=> chore: add dependabot for github actions

.github/workflows/run-integration-tests.yml, CHANGELOG.md, composer.json, src/UsesResolver.php
- `createForHostVersion` has been added to php-parser 4.18 so code can run with both versions [1]
- therefore also bumped the minimum required version to it
However, unrelated some tests in `master` were not working currently, which I also fixed to get the ✅ : 
- Excluded unsupported PHP / Laravel combinations ([used the official docs as reference](https://laravel.com/docs/10.x/releases))
- Allow doctrine/dbal:^4 too
This solved some combination of the integration tests failing, though I'm not 100% sure if dbal truly works with it; it seems none of the feature tests install it and it has no stable release yet 🤔
Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1498 and https://github.com/barryvdh/laravel-ide-helper/issues/1490
- The dev dependency vimeo/psalm is **not** …
=> Add support for nikic/php-parser:^5 and (hopefully) doctrine/dbal:^4

.github/workflows/run-integration-tests.yml, README.md, composer.json
Remove doctrine/dbal:^4 support
Tests fail with:
`PHP Fatal error:  Declaration of Illuminate\Database\PDO\Concerns\ConnectsToDatabase::connect(array $params, $username = null, $password = null, array $driverOptions = []) must be compatible with Doctrine\DBAL\Driver::connect(array $params): Doctrine\DBAL\Driver\Connection in /home/runner/work/laravel-ide-helper/laravel-ide-helper/vendor/laravel/framework/src/Illuminate/Database/PDO/Concerns/ConnectsToDatabase.php on line 22`
This was just recently added, before doctrine/dbal 4.0.0 was released, which happened 1 hour ago and tests don't work now.
Remove it until this is figured.
Marking it as internal change, because this wasn't release yet.
=> Remove doctrine/dbal:^4 support

CHANGELOG.md, composer.json
Hi @barryvdh , it's been almost a year [since 2.13.0 was pushed out](https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.13.0) and I propose we do another release with the current changelog (I found one missing entry which I added):
> ### Changed
> - Official support for Lumen has been dropped [#1425 / mfn](https://github.com/barryvdh/laravel-ide-helper/pull/1425)
> - Refactor resolving of null information for custom casted attribute types [#1330 / wimski](https://github.com/barryvdh/laravel-ide-helper/pull/1330)
> 
> ### Fixed
> - Add support for attribute accessors marked as protected. [#1339 / pindab0ter](https://github.com/barryvdh/laravel-ide-helper/pull/1339)
> - Catch exceptions when loading aliases [#1465 / dongm2ez](https://github.com/barryvdh/laravel-ide-helper/pull/14 …
=> Prepare 2.14.0 release

README.md
Clarified model behaviour when using the --reset option
The documentation currently reads as though the `--reset` option in the `ide-helper:models` command will only add new columns and ignore the current phpdocs. I believe this is misleading, since the `--reset` behaviour appears to overwrite the docs in full whereas not using it just appends newly added columns. This PR clarifies the behaviour.
=> Clarify use of --reset and --smart-reset flags in documentation

composer.json
Neither phpunit 8 nor spatie/phpunit-snapshot-assertions 3 are relevant anymore.
=> Remove outdated dev references to older versions

resources/views/helper.php, resources/views/meta.php
Currently PS inspects all helper files and screems... This PR makes sure it doesn't inspect helper files.
=> disable inspections of helper files

resources/views/helper.php, src/Generator.php
Currently non-facade classes are resulting non functioning autocomplete. The reason of this that an empty class will be defined in the ide helper class, which will be used for the auto-completion. This pull request prevents this behavior by only handling facades in the namespaced part of the helper file.
Unlike #802  this pull request will keep the alias registration.
Fixes #784
=> Fix non-facade classes will result in no autocomplete

src/Console/ModelsCommand.php
In ModelsCommand, belongs to relations are detected as nullable when this column is nullable or has not foreign key constraint.
https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L841-L842
Now read foreign keys is not reset on model loop.
For example. when column x of model A has no foreign key and column x of model B has foreign key, column x of model A may marked as not nullable because column x is recoreded as foreign key by model B.
=> fix belongsTo relation is detected as nullable.

CHANGELOG.md, README.md, resources/views/helper.php, src/Generator.php, tests/RealTimeFacadesTest.php, tests/stubs/facade-0e0385307adf5db34c7986ecbd11646061356ec8.php, tests/stubs/facade-9431b04ec1494fc71a1bc848f020044aba2af7b1.php
This PR generates helper files for real-time facades. It uses the `@mixin` docblock to copy methods from the real class the facades points to.
For example, adding for an real-time facade of the class `App\TestClass` it would generate the following code in the final helper file:
```php
namespace Facades\App {
/**
* @mixin \App\TestClass     */
class TestClass extends \App\TestClass {}
}
```
=> Support generating helper files for real-time facades

src/Console/ModelsCommand.php
This snipet was lost in the 2.12.x => 2.13.x change. Needs to be reintroduced to allow those who use fully qualified db+table names. (Eg, `database.table`)
=> Reintroduce support for multi-db setups

src/Console/ModelsCommand.php
In singlestore we define some strings as
$table->char($columnName, 40)->charset('binary')->collation('binary');
In singelstore, this becomes 'BINARY(40)' instead of 'CHAR(40) CHARACTER SET 'binary' COLLATE 'binary'
This change would allow the generated proeperties to be 'string' instead of 'mixed', as using a string is correct in this case.
=> Support the BINARY(...) database field type

CHANGELOG.md, config/ide-helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Models/CompositeBelongsToVariation.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/Relations/__snapshots__/Test__test__1.php
Fixes #1474, https://github.com/topclaudy/compoships/issues/77
Hello!
This PR adds support for relationships with composite keys. There have been a couple of issues over the years about this but this still has not been resolved (I don't want to have to extend the Artisan command in my app):
- https://github.com/barryvdh/laravel-ide-helper/issues/838
- https://github.com/barryvdh/laravel-ide-helper/issues/706
There's even an open issue on the Compoship side of things (https://github.com/topclaudy/compoships/issues/77) but as the maintainer stated, there really nothing to do on that end.
I understand Laravel does not support composite keys, however, people do use them and this package already provides the ability to define non-Laravel relations so it would be much easier to support this …
=> Add support for composite keys

src/Console/ModelsCommand.php
Relations were not included in the PHPDoc block if they were named `scope` or `scopes`.
=> Accept `scope` & `scopes` as relation

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php
Trying to Add `#[\AllowDynamicProperties]` before class on mixin, as solution to PHPStan errors 
_Note: could add an extra check  `PHP_VERSION_ID>= 80200`, but seems redundant as attributes have backwards compatibility_  
rel #1386
closes #1402
=> Add `AllowDynamicProperties` Attribute to cooperate with php8.2 deprecation

CHANGELOG.md, composer.json
This prepares a smallish 2.15.0 release before we bump to Laravel 10.<latest>/11 and perhaps remove Doctrine.
=> Prepare 2.15 release

composer.json
Alright let's skip to 3.0 as current working version
=> Switch to 3.0 tag

.github/workflows/run-integration-tests.yml, .github/workflows/run-tests.yml, CHANGELOG.md, README.md, composer.json, tests/Console/ModelsCommand/AllowGlobDirectory/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GenerateBasicPhpDocWithEnumDefaults/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GenerateBasicPhpdoc/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GenerateBasicPhpdocCamel/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GenerateBasicPhpdocFinal/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilderWithFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/Interfaces/Models/User.php, tests/Console/ModelsCommand/MagicWhere/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/RelationCountProperties/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/migrations/____posts_table.php
Add support for Laravel 11. Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1509
This is cherry-picked from https://github.com/barryvdh/laravel-ide-helper/pull/1510 by @KentarouTakeda
=> Add support for Laravel 11 

.github/workflows/composer-normalize.yml, .github/workflows/fix-code-style.yml, .github/workflows/run-integration-tests.yml, .github/workflows/run-static-analysis.yml, .github/workflows/run-tests.yml, CHANGELOG.md, composer.json, tests/Console/ModelsCommand/AdvancedCasts/Test.php, tests/Console/ModelsCommand/GenerateBasicPhpDocWithEnumDefaults/Test.php
- Bump minimum PHP version to 8.1 & misc maintenance
Laravel 10 doesn't support 8.0 anyway and our github actions already reflect that and don't test this version
- Remove phpunit 9
It's not required anymore, Laravel 10+ support phpunit 10+
- gha: remove unused matrix dimension `dependency-version` (we use `stability`)
- gha: bump runner os to ubuntu-22.04
- tests: remove outdated version checks
I also took the library and adapted the CHANGELOG slightly, to make it also clear that doctrine/dbal removal actually means Laravel 9 goes out of support, too.
=> Bump minimum PHP version to 8.1 & misc maintenance

phpunit.xml.dist
Fixes the following warning:
> 1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
=> phpunit --migrate-configuration

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Pivot/Models/ModelWithPivot.php, tests/Console/ModelsCommand/Pivot/Models/Pivots/CustomPivot.php, tests/Console/ModelsCommand/Pivot/Test.php, tests/Console/ModelsCommand/Pivot/__snapshots__/Test__test__1.php
This PR add pivot property when using a pivot model on BelongsToMany relation
=> Add pivot class property

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/QueryScopes/Models/Post.php, tests/Console/ModelsCommand/QueryScopes/Models/PostParent.php, tests/Console/ModelsCommand/QueryScopes/Test.php, tests/Console/ModelsCommand/QueryScopes/__snapshots__/Test__test__1.php
This PR fixes the return value of query scope methods that are defined in a parent class of the target model. At the moment the return value contains the class name where the method is located: `@method static \Illuminate\Database\Eloquent\Builder|PostParent active()`, and with this change it correctly becomes `@method static \Illuminate\Database\Eloquent\Builder|Post active()`. See included test for more context.
=> Fix return value of query scopes from parent class

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Pivot/Models/ModelWithPivot.php, tests/Console/ModelsCommand/Pivot/Models/Pivots/CustomPivot.php, tests/Console/ModelsCommand/Pivot/Test.php, tests/Console/ModelsCommand/Pivot/__snapshots__/Test__test__1.php
As pointed out in https://github.com/barryvdh/laravel-ide-helper/pull/1557#issuecomment-2160730489 , there are pending changes from php-cs-fixer not being applied.
Let's apply them!
=> composer fix-style

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/LaravelCustomCasts/Casts/CustomCasterWithStaticReturnType.php, tests/Console/ModelsCommand/LaravelCustomCasts/Models/CustomCast.php, tests/Console/ModelsCommand/LaravelCustomCasts/__snapshots__/Test__test__1.php
For some reason, the `static` keyword as a return type, does not return `isBuiltin()` === true, so a `\\` is added. We need to manually add it to the built in check.
=> Add `static` to `isBuiltin()` check in `ide-helper:models`

src/Console/ModelsCommand.php
Fixed PHPDoc with unknown formatting.
I set `TValue` to `true`, should I use `bool` ?
=> fix: unknown format PHPDoc

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/SimpleCasts/Models/SimpleCast.php, tests/Console/ModelsCommand/SimpleCasts/__snapshots__/Test__test__1.php
Since Laravel 10 + cast `password` as `hashed` by default, the IDE_helper used to set the type of `$user->password` as `mixed`. 
This small PR is to set it to `string`.
=> Fix type of hased model property

composer.json, tests/Console/ModelsCommand/ArrayCastsWithComment/Test.php, tests/Console/ModelsCommand/ArrayCastsWithComment/__snapshots__/Test__test__1.php
Thanks for merging barryvdh/ReflectionDocBlock#17. This pull request closes #1505 
Now that the new version has been published:
* Use the new corrected version for testing, including the `prefer-lowest` tests
* Fix the tests that were marked as incorrect to be correct
I've made the above changes.
=> fix: Model's `--write` duplicates array properties

tests/MethodTest.php
Fixed test failures in Laravel 11.23 and later. The cause is the following changes on the laravel/framework side:
* laravel/framework#52729
* laravel/framework#52762
I addressed the issue by changing the Laravel method that we were testing.
The following points were taken into consideration when selecting the target method:
* It must be a method of the Eloquent `Builder` class, just like before the fix.
* The content does not change between the CI options `prefer-oldest` and `prefer-stable`, and is unlikely to change in the future.
* It must be a method that accepts multiple parameters.
* Some of these parameters must have default values.
By satisfying these conditions, we can perform tests equivalent to `with()`, which was the target of tests before the fix. `upsert` met the conditions, …
=> Fix upstream dependent test failure in Laravel 11.23 and later

src/Console/ModelsCommand.php
`--smart-reset` was removed in #1525 and has no effect in 3.0 and later.
Removing it would be a breaking change, so why not leave the option and make it clear with `--help` that it has no effect?
=> chore: Fix the description of unused option

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Pivot/Models/ModelWithPivot.php, tests/Console/ModelsCommand/Pivot/Models/Pivots/DifferentCustomPivot.php, tests/Console/ModelsCommand/Pivot/__snapshots__/Test__test__1.php
Currently, when you have multiple `belongsToMany` relations with a custom pivot, the accessor will have a single type. This PR ensures that multiple types are allowed. Also the $pivot property should be nullable as it is not always set during runtime.
=> feat(pivot): add support for multiple pivot types when using the same accessor

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/AdvancedCasts/Collections/AdvancedCastCollection.php, tests/Console/ModelsCommand/AdvancedCasts/Enums/AdvancedCastEnum.php, tests/Console/ModelsCommand/AdvancedCasts/Models/AdvancedCast.php, tests/Console/ModelsCommand/AdvancedCasts/__snapshots__/Test__test__1.php
When you have the casts definition in a model like:
```php
protected function casts(): array
{
return [
'options' => AsCollection::using(OptionCollection::class),
'statuses' => AsEnumCollection::of(ServerStatus::class),
];
}
```
then `php artisan ide-helper:models` command will generate the following PHPDoc for the model:
```php
/**
* @property OptionCollection $options
* @property \Illuminate\Support\Collection<int, ServerStatus> $statuses
*/
```
It also supports styles prior to Laravel 11:
```php
protected $casts = [
'options' => AsCollection::class.':'.OptionCollection::class,
'statuses' => AsEnumCollection::class.':'.ServerStatus::class,
];
```
Related to #1553
=> Add support for `AsCollection::using` and `AsEnumCollection::of` casts

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Pivot/Models/ModelWithPivot.php, tests/Console/ModelsCommand/Pivot/__snapshots__/Test__test__1.php
This makes sure that we won't add a class that's already present in the union type for pivots. This can happen when multiple relations use the same Pivot class.
=> fix(pivot): only use unique classes in the pivot union (Fixes #1606)

CHANGELOG.md, config/ide-helper.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/Relations/__snapshots__/Test__testRelationNotNullable__1.php
This PR introduces a new configuration option `enforce_nullable_relationships` to the Laravel IDE Helper package. The purpose of this option is to provide flexibility in how nullable Eloquent relationships are treated during static analysis, helping to avoid false positives when the application logic ensures the presence of related records.
The current behavior of the Laravel IDE Helper package can give unwanted null warnings in applications that ensure data integrity of relationships on non-nullable Eloquent relationship columns. Specifically, the static analysis tool may flag Eloquent relationship objects as nullable even when application logic guarantees that these relationships and their objects are never null. This behavior results in unnecessary and misleading warnings that disrupt …
=> Feature: Add Config Option to Enforce Nullable Relationships

src/Alias.php, src/Macro.php, src/Method.php, tests/MethodTest.php
See issue for expected improvement: https://github.com/barryvdh/laravel-ide-helper/issues/1574
The class `\Eloquent` in `_ide_helper.php` contains methods from `Illuminate\Database\Eloquent\Builder` and `Illuminate\Database\Query\Builder`. The return type for `$this` is replaced with the real class (in case of the Eloquent\Builder already with an additional `|static`). This merge requests replaces `$this` in methods from Query\Builder with the identical return type `Illuminate\Database\Eloquent\Builder|static`. In the context of an `\Eloquent` instance this should be the real behavior and improves the derived types.
=> Improve replacement of return type for methods from Query\Builder

src/Console/ModelsCommand.php, src/Generator.php
After upgrade from PHP 8.3 to 8.4 I get this deprecation error on laravel deprecated log.
```
WARNING: ErrorException: Barryvdh\LaravelIdeHelper\Console\ModelsCommand::getReturnTypeFromDocBlock(): Implicitly marking parameter $reflectorForContext as nullable is deprecated, the explicit nullable type must be used instead in vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php:1305
```
=> Fixed PHP 8.4 deprecation warning

resources/views/helper.php, src/Console/ModelsCommand.php, src/Generator.php, tests/MacroTest.php
This PR removes implicitly nullable parameters because these result in deprecation warnings for PHP 8.4.
https://www.php.net/manual/en/migration84.deprecated.php#migration84.deprecated.core.implicitly-nullable-parameter
=> Fix PHP 8.4 deprecations

src/Generator.php
The `$output` method parameter is not being assigned to the `$this->output` class variable.
=> Assign $output method parameter to $this->output on Generator

resources/views/helper.php
fix: https://github.com/barryvdh/laravel-ide-helper/issues/1572
adding this docbloc for TModel of Eloquent class in ide-helper fix the return type.
=> fix: add @template TModel of static for Eloquent

composer.json, resources/views/helper.php, src/Alias.php
This add all the templates from traits to the Eloquent alias.
=> Add templates to Eloquent

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/AdvancedCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/SimpleCasts/__snapshots__/Test__test__1.php
Add weak default generics of the kind <array-key, mixed> for default casts that returns those generics, i.e. json, array, arrayable and collection casts.
Solves #1614
=> Add weak generics for array type objects

README.md
Make all "note" in README apply quote style. Now, those "note" stand out in text sea.
=> Make all "note" in README apply quote style

CHANGELOG.md, resources/views/helper.php, src/Generator.php
=> Pb30 version var rename

resources/views/helper.php
Tweak whitespace to align them correctly
=> Format IDE helper

README.md
Add some better docs, remove old laravel options.
=> Add TLDR section, update options

php-templates/LICENSE.md, php-templates/README.md, php-templates/configs.php, php-templates/routes.php, php-templates/translations.php, php-templates/views.php, resources/views/meta.php, src/Console/MetaCommand.php, src/Generator.php, src/IdeHelperServiceProvider.php, tests/Console/MetaCommand/MetaCommandTest.php
With https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html we can also supply an expected Return.
We can use this to autocomplete functions like view/config etc.
Downside is that it needs to run often to be useful, eg. when config or views change. But it can still be helpfull.
Prototype done for config.
=> Add phpstorm meta argument hints

resources/views/meta.php, src/Console/MetaCommand.php
When using the PHpstorm Metadata, this sets the user model correctly on thing like `$request->user()`
=> Add meta override for user return types

composer.json, php-templates/auth.php, php-templates/middleware.php, resources/views/meta.php, src/Console/MetaCommand.php
Adds auth, middleware and simplifies the configuration (+fix/add some methods)
=> Add more metadata

src/Macro.php
When a Macro is set for eg. the Client class, we cannot always know the return type. For ClientFactory, we assume the macro is a PendingRequest, even without typehints.
Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1565
=> Feat guess macro types

README.md, config/ide-helper.php, src/Alias.php, src/Generator.php, tests/AliasTest.php
Some packages, like [Filament](https://filamentphp.com), implements their own version of the Macroable trait.
Spatie even made [their own version](https://github.com/spatie/macroable).
This PR allow adding any macro class we want to detect in the config file.
Thanks,
Mathieu.
=> Allow adding custom Macroable classes.

src/Console/ModelsCommand.php
PHPStan requires you to specify the generics in a docblock when using MorphTo (and other relations) like this:
```php
/**
* @return MorphTo<LocationComplex|LocationAccommodation|LocationRoom, $this>
*/
public function location(): MorphTo
{
return $this->morphTo();
}
```
Since this is already in the same model, we can use these generics (if specified) to determine the type of MorphTo. This would save (at least me) the trouble of having to write a custom hook for each polymorphic relation that I use. :)
This will return the following docblock:
```php
/**
* @property-read LocationComplex|LocationAccommodation|LocationRoom $location
*/
```
=> feat: use generics of return type to determine resulting models

src/Console/ModelsCommand.php
Fixes #1657 which was introduced in #1653
=> Check if returnType from docblock is not null

php-templates/configs.php
Fixes config items incorectlly set as `string` due to `'array(...)'` value passed to `gettype` instead of real array
=> Fix for incorrect config item types in meta file

src/Console/ModelsCommand.php
When generating Eloquent annotations on a model that uses a factory, the tool generates an incorrect `$use_factory` property with the following annotation:
`@property-read \App\Models\TFactory|null $use_factory`
Then, when running a static analysis tool (like Larastan), it fails:
PHPDoc tag `@property-read for property App\Models\User::$use_factory contains unknown class App\Models\User\TFactory`.
This pull request introduces a workaround for that problem by filtering out the `getUseFactoryAttribute` method from the reflected methods in `src/Console/ModelsCommand::getPropertiesFromMethods()`.
With the changes from this PR, running `artisan ide-helper:models -n -W -R` in our project root removes the faulty `@property-read` annotations.
Credit for this idea goes to …
=> Prevent generation of incorrect property annotation

src/Console/ModelsCommand.php
fix:
```php
/**
* @return MorphTo<contravariant ModelA|ModelB, $this>
*/
public function reminderable(): MorphTo {
return $this->morphTo(__FUNCTION__, 'entity', 'entity_id');
}
```
From:
```php
* @property-read contravariant ModelA|ModelB $reminderable
```
To:
```php
* @property-read ModelA|ModelB $reminderable ``` Fixes: #1667
=> Fix MorphTo Model Doc Generation

.github/workflows/run-integration-tests.yml, .github/workflows/run-tests.yml, composer.json
Just putting this out there to get ahead of the curve on supporting Laravel 12 when it's released on 24th Feb 2025.
=> Laravel 12 support

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/AdvancedCasts/__snapshots__/Test__test__1.php
Support for Laravel's model `AsArrayObject` cast was added in https://github.com/barryvdh/laravel-ide-helper/pull/1393. It, however, was added using PHP's `\ArrayObject` object when it should be Laravel's `Illuminate\Database\Eloquent\Casts\ArrayObject`.
As it is now, using Laravel's methods like `toArray` throw an error in the editor (like VS Code) saying the method is invalid.
- Laravel's model [`Illuminate\Database\Eloquent\Casts\AsArrayObject`](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Casts/AsArrayObject.php#L28) cast
- [`Illuminate\Database\Eloquent\Casts\ArrayObject`](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Casts/ArrayObject.php#L16)
=> fix: Change AsArrayObject cast to be Laravel's ArrayObject

resources/views/helper.php, src/Alias.php
Currently, Laravel IDE Helper does not generate `extends` declarations for Macroable classes in their DocBlock. For example, `Illuminate\Http\Request` extends `Symfony\Component\HttpFoundation\Request`, but this inheritance is missing in the generated helper file.
As a result, tools like [PHPStan](https://phpstan.org/) or [PHP Intelephense](https://github.com/bmewburn/vscode-intelephense) sonetimes fail to detect the inherited methods and constants, triggering errors or warnings such as:
```php
use Illuminate\Http\Request;
function foo(Request $request)
{
$request->isMethod(Request::METHOD_GET);
}
```
```
Access to undefined constant Illuminate\Http\Request::METHOD_GET
Call to an undefined method Illuminate\Http\Request::isMethod()
```
- **Adds an `extends` declaration** to the DocBlock …
=> Add extends declaration for Macroable classes to fix missing inherited methods

composer.json, resources/views/helper.php, resources/views/meta.php, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/QueryScopes/Models/Comment.php, tests/Console/ModelsCommand/QueryScopes/__snapshots__/Test__test__1.php
(https://laravel-news.com/local-model-scopes-in-laravel-with-the-scope-attribute)
This adds support for the new Scope syntax:
```php
use Illuminate\Database\Eloquent\Attributes\Scope;
#[Scope]
protected function popular(Builder $query): void
{
$query->where('votes', '>', 100);
}
```
=> feat(ModelsCommand): add support for the new Scope attribute

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpDocWithTypedScopeParameter/Models/Comment.php, tests/Console/ModelsCommand/GeneratePhpDocWithTypedScopeParameter/Test.php, tests/Console/ModelsCommand/GeneratePhpDocWithTypedScopeParameter/__snapshots__/Test__test__1.php
This corrects the handling for default float parameter values. At the moment this default values will generate as a string. I also added tests for many typed scenrios in scopes.
Before
```php
/**
* @method static Builder<static>|Comment typed28(?float $value = '1.23')
* /
```
After
```php
/**
* @method static Builder<static>|Comment typed28(?float $value = 1.23)
* /
```
=> fix type change for scope default float parameter

config/ide-helper.php, src/Generator.php, src/Macro.php, tests/Console/GeneratorCommand/GenerateIdeHelper/Test.php
It would allow you to define custom defaults for macros, useful if you work in an environment where return types are not defined.
=> Configurable macro return type defaults

README.md
This pull request updates the project's readme to explicitly clarify that Laravel 12 is supported by the 3.x branch, specifically since version [3.5.5](https://github.com/barryvdh/laravel-ide-helper/pull/1672). Previously, the documentation only mentioned support for Laravel 10 and 11, which could lead to confusion or uncertainty for users working with Laravel 12. This change provides accurate and up-to-date information, helping users quickly understand compatibility.
- This change requires a documentation update.
- Update the README.md.
=> docs(readme): add Laravel 12 support information

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqn/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/SoftDeletes/__snapshots__/Test__test__1.php
Fixed wrong php doc being generated for `withTrashed` method when SoftDeletes trait is used in a model.
Previously this doc looked like this (missing parameter):
` * @method static \Illuminate\Database\Eloquent\Builder<static>|Simple withTrashed()`
When it should look like this (taken from the trait itself)
` * @method static \Illuminate\Database\Eloquent\Builder<static>|Simple withTrashed(bool $withTrashed = true)`
=> fix: Fixed wrong doc for SoftDeletes `withTrashed` method

tests/Console/GeneratorCommand/AbstractGeneratorCommand.php, tests/Console/ModelsCommand/AbstractModelsCommand.php, tests/Console/ModelsCommand/ModelHooks/Test.php, tests/Console/ModelsCommand/ModelHooks/__snapshots__/Test__test__1.php, tests/SnapshotPhpDriver.php, tests/SnapshotTxtDriver.php, tests/TestCase.php
I think it would make collaborations easier if other OS(`line feed issue`) were supported in testing.
=> Support other OS on tests

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/AdvancedCasts/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/SimpleCasts/__snapshots__/Test__test__1.php
Laravel casts using `'encrypted'` always result in a string. This is because Laravel encrypts the value directly without serialization. As a result, the output will never be anything other than a string.
Ref in HasAttributes.php:
=> fix(ModelsCommand): use 'string' as realType for 'encrypted' casts

README.md
Fixes typo introduced in #1712
=> Fix `methodsto` typo in README

README.md, src/Method.php
- Fixed 'seperate' to 'separate' in README.md (2 occurrences)
- Fixed 'columname' to 'columnname' in README.md (2 occurrences)
- Fixed 'Wether' to 'Whether' in src/Method.php PHPDoc comments (2 occurrences)
=> Fix typos in documentation and code comments
