src/Console/ModelsCommand.php
When define a class(table) , we will add some comment information to the property (field), the comment information was useful for coder who has  bad memory.so ,I think we'd better show the comment at the end of  * @property  line.
I'm a Chinese, most of my team was Chinese too,   the comment information was written by Chinese, so , it's helpful!
－－－－－－－－－－－－－－－－－－－－－－－－－
当我们定义一个类(表)的时候，我们会给对象(字段)加上一些注释信息，这些注释信息对记忆力不好的程序员很有用，所以我认为我们可以在属性行的尾部加入注释信息
我是个中国人，我团队中的大部分人也是中国人，这些注释信息是中文写的，对他们很有帮助。
=> Update ModelsCommand.php , Add COMMENT info.

readme.md
Gives errors for people just copy-pasting ;)
=> JSON standard does not allow trailing comma

readme.md
With this information it's much easier to install.
=> Automatic phpDocs for models: added copy/past

src/Console/ModelsCommand.php
https://github.com/barryvdh/laravel-ide-helper/issues/287
=> fix(models-command): check for default reflectionparameter value

src/Generator.php
=> Fix Auth driver detection in Laravel 5.2

src/Generator.php
Another autoloader throw exception if aliases not exists.
=> Don't use force aliases loading

src/Generator.php
Reverts barryvdh/laravel-ide-helper#303
=> Revert "Don't use force aliases loading"

src/Console/ModelsCommand.php
=> recover model's whereXXX() helper function

src/Console/ModelsCommand.php
It's help author to close many issues! )
Like: #269, #259, #248, #209, #191, #74, 
and https://github.com/laravel/framework/issues/7558 )))
etc. maybe
=> Add extend \Eloquent for ide-helper:models command

src/Console/ModelsCommand.php
Add this missing relationship.
Works well with my current project.
=> Add hasManyThrough relationship

src/Console/ModelsCommand.php
=> add support for $casts

src/Console/ModelsCommand.php
Oops, looks like I forgot to commit one call to the new method. This is related to #377.
=> hotfix for type overrides

readme.md
just a couple spelling fixes for the readme file.
=> readme spelling

resources/views/helper.php, src/Generator.php
=> Add namespaced aliases

src/Console/ModelsCommand.php
Using Doctrine notNull on column, this pull request implement the detection of Nullable.
It does it for the properties of the model and the relation that are using the property.
Fixes #407
=> Implements Nullable

readme.md
From time to time I see confusion about this. 
Fresh example: https://github.com/barryvdh/laravel-ide-helper/issues/514
=> Note for \Eloquent

src/Console/ModelsCommand.php
=> return eloquent builder instead of plain database builder

src/Console/ModelsCommand.php
this patch implements auto-completion  for the SoftDeletes trait methods
=> generate methods for the SoftDeletes trait

src/Console/ModelsCommand.php
=> Softdelete eloquent builder

composer.json
allow to install within laravel 5.5
=> added L55-support

src/Console/GeneratorCommand.php, src/Console/MetaCommand.php, src/Console/ModelsCommand.php
Command fire method is now handle
=> Fix for Laravel 5.5

src/Console/EloquentCommand.php, src/Console/GeneratorCommand.php, src/Eloquent.php, src/IdeHelperServiceProvider.php
for adding the `@mixin \Eloquent` to the Illuminate\Database\Eloquent\Model
=> Add an eloquent command

readme.md
Updated with the latest CodeIntel that actually works.
=> update to the latest code intel

resources/views/helper.php, resources/views/meta.php
I think this is useful for debugging.
=> Show time in generated files

src/Eloquent.php
Reverts barryvdh/laravel-ide-helper#624
=> Revert "Fixes a bug where a missing DocBlock caused errors"

resources/views/helper.php
See https://laravel.com/docs/5.6/migrations#modifying-columns
=> add change modifier

src/Alias.php
Did not check method duplication by used_methods against macros, I added it.
=> fix: Macro methods are duplicated registration.

src/Console/ModelsCommand.php
In my applications, sometimes I have the following scenario:
```php
/**
* @return \Illuminate\Database\Eloquent\Relations\HasMany
*/
public function tags()
{
return $this->hasMany(Tag::class);
}
/**
* @return \Illuminate\Database\Eloquent\Relations\HasMany
*/
public function redTags()
{
return $this->tags()->where('color', 'red');
}
```
Currently `redTags` is not included in the generated output.
This pull request addresses that by checking the return type of the functions when scanning for relations on a model. (both native return type and fallback in the `@return` docblock)
=> Nested eloquent relations detection.

src/Console/ModelsCommand.php
add cast (string) to disable bug ($type can be null)
=> Fix Bug PHP 7.3 & L5.8

src/Console/MetaCommand.php
=> Fixed meta not working with app()->makeWith()

src/Console/ModelsCommand.php
Sorry this is a bit nitpicky 😅
=> ModelsCommand: Remove question mark

config/ide-helper.php
A quick win to prevent manual fixing after publishing the config.
=> Fix the identation in the config

config/ide-helper.php
=> Remove monolog configuration

src/Console/ModelsCommand.php
__toString function has been DEPRECATED as of PHP 7.4.0
=> __toString function has been DEPRECATED

src/Method.php, tests/MethodTest.php
Add splat operator (...) support.
#747
=> Add splat operator (...) support

tests/Console/ModelsCommand/GenerateBasicPhpdoc/Test.php, tests/Console/ModelsCommand/Getter/Models/Simple.php, tests/Console/ModelsCommand/Getter/Test.php, tests/Console/ModelsCommand/Relations/Models/Simple.php, tests/Console/ModelsCommand/Relations/ModelsOtherNamespace/AnotherModel.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/SoftDeletes/Models/Simple.php, tests/Console/ModelsCommand/SoftDeletes/Test.php, tests/Console/ModelsCommand/migrations/____posts_table.php, tests/Console/ModelsCommand/migrations/____simple_table.php
Summary of tests added:
- be more systematic when testing discrete column types
- relations of models
- model in another namespace gets correctly qualified
- softdeletes
- getters
=> Add more tests

src/Console/ModelsCommand.php
During Development i got an Error. It was not easy to identify the problem without the StackStrace
=> Improve Error Reporting for easy debugging

tests/Console/ModelsCommand/Getter/Test.php, tests/Console/ModelsCommand/Relations/Test.php, tests/Console/ModelsCommand/SoftDeletes/Test.php, tests/Console/ModelsCommand/migrations/____simple_table.php
=> [TESTS] Fix typo in migration 🤦‍♂️ and adapt tests

tests/Console/ModelsCommand/ResetAndSmartReset/Models/Simple.php, tests/Console/ModelsCommand/ResetAndSmartReset/Test.php
=> [TESTS] Cover reset and smart-reset options

tests/Console/ModelsCommand/ResetAndSmartReset/Test.php
Just keeping things in order here
=> [TESTS] Fix after recent merged "stepping on each others toes"

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Interfaces/Models/User.php, tests/Console/ModelsCommand/Interfaces/Test.php
We've been running into this over at https://github.com/psalm/psalm-plugin-laravel/issues/21, and I think this might be appropriate to include here?
=> if a model implements interfaces, include them in the stub

config/ide-helper.php, src/Console/ModelsCommand.php
Feature was added with https://github.com/barryvdh/laravel-ide-helper/pull/921
=> Document that model_locations/dir now supports glob

resources/views/meta.php
This works in phpstorm 2020.1.
Closes #684
=> add optional

.github/workflows/composer-normalize.yml, composer.json
This PR normalizes the `composer.json` by running https://github.com/ergebnis/composer-normalize and adds a GitHub action that keeps the `composer.json` normalized.
=> composer normalize

composer.json, grumphp.yml, src/Alias.php, src/Console/EloquentCommand.php, src/Console/GeneratorCommand.php, src/Console/MetaCommand.php, src/Console/ModelsCommand.php, src/Eloquent.php, src/Generator.php, src/IdeHelperServiceProvider.php, src/Method.php
per https://github.com/barryvdh/laravel-ide-helper/pull/960#issuecomment-647607851
=> chore: psr12

composer.json
=> composer.json: bump branch-alias as 2.7 has already been released

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/Builders/EMaterialQueryBuilder.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/Models/Post.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/Test.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/__snapshots__/Test__test__1.php
Fixes #992 
Disabled generating models phpdoc using imported name in external file, except for the models own class name.
=> [Models] Fixed wrong imported name

src/Console/ModelsCommand.php
AFAIK never had.
See https://github.com/laravel/framework/blob/c1ec18723e763120aa4e816072beca396d298db1/src/Illuminate/Database/Connection.php#L892
=> getDoctrineSchemaManager doesn't take an argument

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/DynamicRelations/Models/Dynamic.php, tests/Console/ModelsCommand/DynamicRelations/OtherModels/Account.php, tests/Console/ModelsCommand/DynamicRelations/Test.php, tests/Console/ModelsCommand/DynamicRelations/__snapshots__/Test__test__1.php, tests/SnapshotPhpDriver.php, tests/SnapshotTxtDriver.php
Relationships should be detected based on static analysis, so dynamic properties should not be an issue.
(Test currently failing)
=> Test dynamic relationships

tests/TestCase.php
=> [TESTS] Remove L5.5 workaround

src/IdeHelperServiceProvider.php
=> Remove unused `use` vars

src/Console/MetaCommand.php
Sorry, just discovered that I missed something in https://github.com/barryvdh/laravel-ide-helper/pull/996/files#diff-7ecb847253b042da4c0c53c558453a67R61 🤦‍♀️
=> Fix type for new meta command 🤷‍♀️

tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/Models/Post.php, tests/Console/ModelsCommand/GeneratePhpdocWithForcedFqn/__snapshots__/Test__test__1.php
This fixes https://github.com/barryvdh/laravel-ide-helper/runs/1055498817 from master
=> Run `composer fix-style` and `vendor/bin/phpunit -d --update-snapshots` to solve failed build

.github/ISSUE_TEMPLATE/1_Bug_report.md, .github/ISSUE_TEMPLATE/2_Feature_request.md, .github/ISSUE_TEMPLATE/3_Support_question.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add github issue/PR templates

README.md, config/ide-helper.php, src/Factories.php, tests/Factories/AllTest.php
=> [LARAVEL 8] include_factory_builders does not work anymore (#1047)

.github/workflows/run-integration-tests.yml
Lumen 8 is available, and should be tested as well.
=> Add Lumen 8 to integration test

resources/views/helper.php, tests/MethodTest.php
=> Test enhancement

composer.json
Stable 2 has been released some time ago
=> composer.json: remove -dev from composer/composer dependency

CHANGELOG.md
Assuming we already go for 2.9.0 in the next release.
=> Update changelog / releases

CHANGELOG.md, tests/Console/ModelsCommand/UnionTypes/Test.php
=> Update changelog and also automagically apply style fix

src/Console/ModelsCommand.php
Removed extra quotation mark on error message
N/A
=> Remove extra single quote

CHANGELOG.md
=> chore: adapt for release of 2.9.1

CHANGELOG.md
=> Add missing changelog entry for #1184

CHANGELOG.md
Suggesting to roll a new release after merging this one
=> chore: prepare 2.9.2 release

src/Console/ModelsCommand.php, tests/Console/ModelsCommand/Factories/CustomSpace/ModelWithCustomNamespaceFactory.php, tests/Console/ModelsCommand/Factories/Factories/ModelWithFactoryFactory.php, tests/Console/ModelsCommand/Factories/Models/ModelWithCustomNamespace.php, tests/Console/ModelsCommand/Factories/Models/ModelWithFactory.php, tests/Console/ModelsCommand/Factories/Test.php, tests/Console/ModelsCommand/Factories/__snapshots__/Test__test__1.php
In response to a discussion I started: https://github.com/barryvdh/laravel-ide-helper/pull/1196#issuecomment-812173816.
=> Support both customized namespace factories as well as default resolvable ones

CHANGELOG.md
=> chore: prepare changelog for 2.9.3 release

CHANGELOG.md, composer.json
- Add support for custom casts that using `Castable` [#1287 / binotaliu](https://github.com/barryvdh/laravel-ide-helper/pull/1287)
- Added Laravel 9 support [#1297 / rcerljenko](https://github.com/barryvdh/laravel-ide-helper/pull/1297)
=> Prepare 2.12 release

CHANGELOG.md
I suggest we push out a minor release.
- Properly handle `Castable`s without return type. [#1306 / binotaliu](https://github.com/barryvdh/laravel-ide-helper/pull/1306)
=> Prepare 2.12.1 patch release

.github/workflows/run-integration-tests.yml
Test Laravel 9 now it's released.
=> Test 9.* integration

README.md
Based on the discussion in https://github.com/barryvdh/laravel-ide-helper/issues/1347
=> readme: explicitly state supported version

.github/workflows/run-integration-tests.yml, src/Console/ModelsCommand.php
Changed with https://github.com/laravel/laravel/commit/c1092ec084bb294a61b0f1c2149fddd662f1fc55
=> Use dev instead of stable

CHANGELOG.md
I've already updated the release page to contain this changelog -> https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.13.0
=> Update changelog after new release 2.13.0

tests/Console/ModelsCommand/DoesNotGeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithExternalEloquentBuilder/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithFqnInExternalFile/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php, tests/Console/ModelsCommand/Interfaces/__snapshots__/Test__test__1.php
I just ran `composer test-regenerate`
https://github.com/barryvdh/laravel-ide-helper/pull/1456
=> Fix tests for edc422cd2e62c11802668cc1460ff9ab247d145a

src/Generator.php
Extend Generator.php for skipping swoole
=> skip swoole, otherwise fatal error

.gitattributes
and make up for the missing php-cs-fixer changes
The rest of the changes is just:
- sorted alphabetically
- align the `export-ignore` column
Doesn't require a changelog or so update.
=> Adjust gitattribute

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/Models/FinalPost.php, tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php
Fixes final class keyword (https://github.com/barryvdh/laravel-ide-helper/issues/1516)
=> Fix final class keyword

CHANGELOG.md, README.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/ResetAndSmartReset/Test.php
See https://github.com/barryvdh/laravel-ide-helper/pull/1523#issuecomment-1952313183
=> Remove `--smart-reset` completely

CHANGELOG.md
Prepare 3.0 release for upcoming Laravel 11 release.
=> Prepare 3.0 release

config/ide-helper.php
- Terminate all descriptions with a dot .
- Update outdated descriptions
- Add missing examples
- Only capitalize proper names
=> Improve config file

composer.json
=> Bump dev alias to 3.2

CHANGELOG.md, src/Console/ModelsCommand.php, tests/Console/ModelsCommand/ResetAndSmartReset/Models/Simple.php, tests/Console/ModelsCommand/ResetAndSmartReset/__snapshots__/Test__testNoReset__1.php, tests/Console/ModelsCommand/ResetAndSmartReset/__snapshots__/Test__testReset__1.php
Smarter reset, Fixes https://github.com/barryvdh/laravel-ide-helper/issues/1598
=> Smarter reset

.github/PULL_REQUEST_TEMPLATE.md
This seems redundant since the CHANGELOG is generated automatically.
=> docs(pr): remove the changelog checklist item

src/Alias.php
The class itself can also contain Template tags. https://github.com/barryvdh/laravel-ide-helper/issues/1572#issuecomment-2565371299
=> Also add eloquent template tags from base class

php-templates/auth.php, src/Console/MetaCommand.php
Tweak auth contract, catch errors
=> Catch meta, tweak auth

src/Alias.php
If a macro is invalid, ignore it.
=> Check if macro is valid

src/Console/MetaCommand.php
Resolves the issue when deprecation warnings occur.
=> fix(meta): ignore aliases in the autoloader (Fixes #1671)

.gitattributes
Avoid `.php-cs-fixer`  files on vendor
=> Update .gitattributes - avoid all `.php-cs-fixer` files on vendor

.github/workflows/run-tests.yml
=> Add php 8.5 support
